export const commonEn = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Skip to content',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.loading': 'Loading…',
  'common.details': 'Technical details',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.discard': 'Discard',
  'common.close': 'Close',
  'common.remove': 'Remove',
  'common.add': 'Add',
  'common.reload': 'Reload from disk',
  'common.optional': 'optional',
  'error.offline.title': "Can't reach the local server",
  'error.offline.body': "The backend at :8000 didn't answer. Check that `npm run dev` is running and try again.",
  'error.chatDisabled.title': 'Chat is turned off',
  'error.chatDisabled.body': 'The `chat` flag is off in ~/.ooc-local/config.yaml. Turn it on and restart the server.',
  'error.unexpected.title': 'Something broke on this screen',
  'error.unexpected.body': "The action didn't complete. Try again; if it repeats, check the server log.",

  // Session list
  'sessions.heading': 'Your sessions',
  'sessions.loading': 'Loading sessions…',
  'sessions.empty.title': 'No sessions yet',
  'sessions.empty.body': 'Pick a scenario above and start your first session.',
  'sessions.error.title': "Couldn't load your sessions",
  'sessions.error.body': "The session list didn't come back from the server. Your saved sessions are intact.",
  'sessions.item.turnsZero': 'Not started',
  'sessions.item.turnsOne': '1 turn',
  'sessions.item.turnsOther': '{count} turns',
  'sessions.item.meta': '{turns} · last played {when}',
  'sessions.item.open': 'Continue {scenario}',
  'sessions.new.heading': 'New session',
  'sessions.new.scenarioLabel': 'Scenario',
  'sessions.new.submit': 'Start session',
  'sessions.new.submitting': 'Starting…',
  'sessions.new.error': "Couldn't start the session. Nothing was saved — try again.",
  'sessions.new.scenariosError': "Couldn't load scenarios",
  'sessions.builderLink': 'Open the builder',
} as const

export const commonPtBr: Record<keyof typeof commonEn, string> = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Pular para o conteúdo',
  'common.retry': 'Tentar de novo',
  'common.cancel': 'Cancelar',
  'common.back': 'Voltar',
  'common.loading': 'Carregando…',
  'common.details': 'Detalhes técnicos',
  'common.save': 'Salvar',
  'common.delete': 'Deletar',
  'common.discard': 'Descartar',
  'common.close': 'Fechar',
  'common.remove': 'Remover',
  'common.add': 'Adicionar',
  'common.reload': 'Recarregar do disco',
  'common.optional': 'opcional',
  'error.offline.title': 'Não consegui falar com o servidor local',
  'error.offline.body': 'O backend em :8000 não respondeu. Confira se o `npm run dev` está rodando e tente de novo.',
  'error.chatDisabled.title': 'O chat está desligado',
  'error.chatDisabled.body': 'A flag `chat` está desligada em ~/.ooc-local/config.yaml. Ligue e reinicie o servidor.',
  'error.unexpected.title': 'Alguma coisa quebrou nesta tela',
  'error.unexpected.body': 'A ação não terminou. Tente de novo; se repetir, olhe o log do servidor.',

  // Session list
  'sessions.heading': 'Suas sessões',
  'sessions.loading': 'Carregando sessões…',
  'sessions.empty.title': 'Nenhuma sessão ainda',
  'sessions.empty.body': 'Escolha um cenário acima e comece sua primeira sessão.',
  'sessions.error.title': 'Não consegui carregar suas sessões',
  'sessions.error.body': 'A lista de sessões não voltou do servidor. Suas sessões salvas estão intactas.',
  'sessions.item.turnsZero': 'Não começou',
  'sessions.item.turnsOne': '1 turno',
  'sessions.item.turnsOther': '{count} turnos',
  'sessions.item.meta': '{turns} · jogada {when}',
  'sessions.item.open': 'Continuar {scenario}',
  'sessions.new.heading': 'Nova sessão',
  'sessions.new.scenarioLabel': 'Cenário',
  'sessions.new.submit': 'Começar sessão',
  'sessions.new.submitting': 'Começando…',
  'sessions.new.error': 'Não consegui começar a sessão. Nada foi salvo — tente de novo.',
  'sessions.new.scenariosError': 'Não consegui carregar os cenários',
  'sessions.builderLink': 'Abrir o builder',
}
