export const gameEn = {
  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Loading session…',
  'game.back': 'Back to sessions',
  'game.prologue.label': 'Prologue',
  'game.empty.hint': 'Your turn. Type what you do or say.',
  'game.input.label': 'Your action',
  'game.input.send': 'Send',
  'game.input.sending': 'Narrating…',
  'game.input.hint': 'Enter sends · Shift+Enter for a new line',
  'game.suggest.regionLabel': 'Suggested actions',
  'game.suggest.send.aria': 'Send: {text}',
  'game.suggest.edit': 'Edit',
  'game.suggest.edit.aria': 'Edit: {text}',
  'game.mode.regionLabel': 'Input mode',
  'game.mode.do': 'Do',
  'game.mode.say': 'Say',
  'game.mode.story': 'Story',
  'game.mode.do.hint': 'What you try to do. The narrator decides how it turns out.',
  'game.mode.say.hint': 'What you say out loud, word for word.',
  'game.mode.story.hint': 'Text that enters the story as something that happened.',
  'game.input.placeholder.do': 'What do you do?',
  'game.input.placeholder.say': 'What do you say?',
  'game.input.placeholder.story': 'What happens next?',
  'game.turn.playerLabel': 'You',
  'game.turn.narratorLabel': 'Narrator',
  'game.turn.thinking': 'The narrator is writing…',
  'game.turn.done': 'Turn {index} done',
  'game.turn.partial': 'Incomplete turn',
  'game.turn.error': 'The turn stopped halfway',
  'game.turn.errorBody': "The narrator didn't finish. Your message was kept — send it again.",
  'game.scrollToLatest': 'Jump to latest',
  'game.notFound.title': 'Session not found',
  'game.notFound.body': "This session doesn't exist anymore. Go back and pick another one.",
  'game.sprite.alt': '{character}, {emotion}',
  'game.stage.hide': 'Hide the artwork',
  'game.stage.show': 'Show the artwork',
  'game.scene.announce': 'Scene: {background}. On screen: {characters}.',
  'game.scene.announceBackground': 'Scene: {background}.',
  'game.scene.announceCharacters': 'On screen: {characters}.',
  'game.scene.characterEmotion': '{character} ({emotion})',
  'game.scene.empty': 'no one',
  'game.cast.label': 'In scene',
  'game.cast.empty': 'No one',
  'game.cast.unavailable': 'Not known yet',
  'game.cast.announce': 'Now in scene: {characters}.',
  'game.cast.regionLabel': 'Characters in scene',
  'game.info.label': 'INFO — what they think',
  'game.info.regionLabel': 'What the characters in scene think',
  'game.info.pending': 'Nobody read yet. Play a turn and the narrator starts tracking how each one feels.',
  'game.info.unknown': 'Not read yet',
  'game.info.event': 'Last: {event}',

  // HUD
  'hud.turn': 'Turn',
  'hud.location': 'Location',
  'hud.time': 'Time',
  'hud.weather': 'Weather',
  'hud.placeholder': '—',
  'hud.unavailable': 'Not tracked yet',
  'hud.stale': 'Showing the last known state',
  'hud.announce': 'Turn {turn}, {location}, {time}, {weather}',
  'hud.stats.regionLabel': 'Player stats',
  'hud.stat.value': '{value}/{max}',
  'hud.stat.level': 'Level: {level}',
  'hud.stats.change': '{name} now {value}',
  'hud.stats.announce': 'Stats: {changes}.',
  'hud.weather.clear': 'Clear',
  'hud.weather.cloudy': 'Cloudy',
  'hud.weather.rain': 'Rain',
  'hud.weather.storm': 'Storm',
  'hud.weather.snow': 'Snow',
  'hud.weather.fog': 'Fog',
  'hud.weather.night': 'Night',
  'hud.weather.unknown': 'Unknown',

  // Turn text
  'turnText.speakerLabel': '{name} says',
  'turnText.narrationLabel': 'Narration',
  'turnText.rawFallback': 'Shown as the narrator wrote it',
} as const

export const gamePtBr: Record<keyof typeof gameEn, string> = {
  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Carregando sessão…',
  'game.back': 'Voltar para as sessões',
  'game.prologue.label': 'Prólogo',
  'game.empty.hint': 'Sua vez. Escreva o que você faz ou fala.',
  'game.input.label': 'Sua ação',
  'game.input.send': 'Enviar',
  'game.input.sending': 'Narrando…',
  'game.input.hint': 'Enter envia · Shift+Enter quebra linha',
  'game.suggest.regionLabel': 'Ações sugeridas',
  'game.suggest.send.aria': 'Enviar: {text}',
  'game.suggest.edit': 'Editar',
  'game.suggest.edit.aria': 'Editar: {text}',
  'game.mode.regionLabel': 'Modo de escrita',
  'game.mode.do': 'Ação',
  'game.mode.say': 'Fala',
  'game.mode.story': 'Narração',
  'game.mode.do.hint': 'O que você tenta fazer. O narrador decide como termina.',
  'game.mode.say.hint': 'O que você fala em voz alta, palavra por palavra.',
  'game.mode.story.hint': 'Texto que entra na história como algo que aconteceu.',
  'game.input.placeholder.do': 'O que você faz?',
  'game.input.placeholder.say': 'O que você diz?',
  'game.input.placeholder.story': 'O que acontece?',
  'game.turn.playerLabel': 'Você',
  'game.turn.narratorLabel': 'Narrador',
  'game.turn.thinking': 'O narrador está escrevendo…',
  'game.turn.done': 'Turno {index} pronto',
  'game.turn.partial': 'Turno incompleto',
  'game.turn.error': 'O turno parou no meio',
  'game.turn.errorBody': 'O narrador não terminou. Sua mensagem foi guardada — mande de novo.',
  'game.scrollToLatest': 'Ir para o mais recente',
  'game.notFound.title': 'Sessão não encontrada',
  'game.notFound.body': 'Essa sessão não existe mais. Volte e escolha outra.',
  'game.sprite.alt': '{character}, {emotion}',
  'game.stage.hide': 'Esconder a arte',
  'game.stage.show': 'Mostrar a arte',
  'game.scene.announce': 'Cena: {background}. Em cena: {characters}.',
  'game.scene.announceBackground': 'Cena: {background}.',
  'game.scene.announceCharacters': 'Em cena: {characters}.',
  'game.scene.characterEmotion': '{character} ({emotion})',
  'game.scene.empty': 'ninguém',
  'game.cast.label': 'Em cena',
  'game.cast.empty': 'Ninguém',
  'game.cast.unavailable': 'Ainda não se sabe',
  'game.cast.announce': 'Agora em cena: {characters}.',
  'game.cast.regionLabel': 'Personagens em cena',
  'game.info.label': 'INFO — o que pensam',
  'game.info.regionLabel': 'O que os personagens em cena pensam',
  'game.info.pending': 'Ninguém lido ainda. Jogue um turno e o narrador começa a acompanhar o que cada um sente.',
  'game.info.unknown': 'Ainda não lido',
  'game.info.event': 'Último: {event}',

  // HUD
  'hud.turn': 'Turno',
  'hud.location': 'Local',
  'hud.time': 'Hora',
  'hud.weather': 'Clima',
  'hud.placeholder': '—',
  'hud.unavailable': 'Ainda não rastreado',
  'hud.stale': 'Mostrando o último estado conhecido',
  'hud.announce': 'Turno {turn}, {location}, {time}, {weather}',
  'hud.stats.regionLabel': 'Atributos do jogador',
  'hud.stat.value': '{value}/{max}',
  'hud.stat.level': 'Nível: {level}',
  'hud.stats.change': '{name} agora {value}',
  'hud.stats.announce': 'Atributos: {changes}.',
  'hud.weather.clear': 'Limpo',
  'hud.weather.cloudy': 'Nublado',
  'hud.weather.rain': 'Chuva',
  'hud.weather.storm': 'Tempestade',
  'hud.weather.snow': 'Neve',
  'hud.weather.fog': 'Neblina',
  'hud.weather.night': 'Noite',
  'hud.weather.unknown': 'Desconhecido',

  // Turn text
  'turnText.speakerLabel': '{name} diz',
  'turnText.narrationLabel': 'Narração',
  'turnText.rawFallback': 'Mostrado como o narrador escreveu',
}
