const en = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Skip to content',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.loading': 'Loading…',
  'common.details': 'Technical details',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.discard': 'Discard',
  'common.close': 'Close',
  'common.remove': 'Remove',
  'common.add': 'Add',
  'common.reload': 'Reload from disk',
  'common.optional': 'optional',
  'error.offline.title': "Can't reach the local server",
  'error.offline.body': "The backend at :8000 didn't answer. Check that `npm run dev` is running and try again.",
  'error.chatDisabled.title': 'Chat is turned off',
  'error.chatDisabled.body': 'The `chat` flag is off in ~/.ooc-local/config.yaml. Turn it on and restart the server.',
  'error.unexpected.title': 'Something broke on this screen',
  'error.unexpected.body': "The action didn't complete. Try again; if it repeats, check the server log.",

  // Session list
  'sessions.heading': 'Your sessions',
  'sessions.loading': 'Loading sessions…',
  'sessions.empty.title': 'No sessions yet',
  'sessions.empty.body': 'Pick a scenario above and start your first session.',
  'sessions.error.title': "Couldn't load your sessions",
  'sessions.error.body': "The session list didn't come back from the server. Your saved sessions are intact.",
  'sessions.item.turnsZero': 'Not started',
  'sessions.item.turnsOne': '1 turn',
  'sessions.item.turnsOther': '{count} turns',
  'sessions.item.meta': '{turns} · last played {when}',
  'sessions.item.open': 'Continue {scenario}',
  'sessions.new.heading': 'New session',
  'sessions.new.scenarioLabel': 'Scenario',
  'sessions.new.submit': 'Start session',
  'sessions.new.submitting': 'Starting…',
  'sessions.new.error': "Couldn't start the session. Nothing was saved — try again.",
  'sessions.new.scenariosError': "Couldn't load scenarios",
  'sessions.builderLink': 'Open the builder',

  // Builder list
  'builder.documentTitle': 'Builder — ooc-local',
  'builder.list.heading': 'Your scenarios',
  'builder.list.back': 'Back to sessions',
  'builder.list.loading': 'Loading scenarios…',
  'builder.list.empty.title': 'No scenarios yet',
  'builder.list.empty.body':
    'A scenario is a folder in scenarios/. Create one here, or drop a folder there and reload.',
  'builder.list.error.title': "Couldn't load your scenarios",
  'builder.list.error.body': "The folder list didn't come back from the server. Nothing on disk was changed.",
  'builder.list.reload': 'Reload from disk',
  'builder.list.reloaded': 'Scenario list reloaded from disk',
  'builder.list.item.meta': '{starts} · {characters}',
  'builder.list.item.startsOne': '1 start',
  'builder.list.item.startsOther': '{count} starts',
  'builder.list.item.charactersZero': 'no characters',
  'builder.list.item.charactersOne': '1 character',
  'builder.list.item.charactersOther': '{count} characters',
  'builder.list.item.edit': 'Edit {scenario}',
  'builder.list.item.broken': "This folder can't be opened",
  'builder.list.item.brokenBody':
    "{reason}. Fix the file on disk and reload — the builder won't overwrite what it can't read.",
  'builder.list.item.reasonUnknown': 'Unreadable file',
  'builder.list.item.coverAlt': 'Cover of {scenario}',
  'builder.create.locale.en': 'English',
  'builder.create.locale.ptBr': 'Portuguese (Brazil)',
  'builder.list.empty.action': 'Create a scenario',
  'builder.create.heading': 'New scenario',
  'builder.create.nameLabel': 'Name',
  'builder.create.namePlaceholder': 'The name players see',
  'builder.create.folderLabel': 'Folder',
  'builder.create.folderHint': 'Folder name inside scenarios/. Lowercase letters, numbers and hyphens.',
  'builder.create.localeLabel': 'Scenario language',
  'builder.create.submit': 'Create scenario',
  'builder.create.submitting': 'Creating…',
  'builder.create.error.nameRequired': 'Give the scenario a name.',
  'builder.create.error.invalidFolder': 'Use only lowercase letters, numbers and hyphens.',
  'builder.create.error.duplicate': 'The folder {folder} already exists. Pick another one.',
  'builder.create.error.failed': "Couldn't create the scenario. Nothing was written to disk — try again.",
  'builder.create.success': 'Scenario {name} created',
  'builder.duplicate.action': 'Duplicate',
  'builder.duplicate.title': 'Duplicate {scenario}',
  'builder.duplicate.body': 'Copies the whole folder, media included.',
  'builder.duplicate.folderLabel': 'New folder',
  'builder.duplicate.submit': 'Duplicate',
  'builder.duplicate.submitting': 'Duplicating…',
  'builder.duplicate.success': '{scenario} duplicated into {folder}',
  'builder.duplicate.error': "Couldn't duplicate. The original folder wasn't touched — try again.",
  'builder.delete.action': 'Delete',
  'builder.delete.title': 'Delete {scenario}?',
  'builder.delete.body':
    'The whole scenarios/{folder} folder goes away, media included. Sessions already played keep their history but stop opening.',
  'builder.delete.confirmLabel': 'Type {folder} to confirm',
  'builder.delete.submit': 'Delete scenario',
  'builder.delete.submitting': 'Deleting…',
  'builder.delete.success': '{scenario} deleted',
  'builder.delete.error':
    "Couldn't delete the folder. Nothing was removed — check that no other program has the files open.",

  // Builder editor
  'builder.editor.documentTitle': '{scenario} — builder — ooc-local',
  'builder.editor.back': 'Back to scenarios',
  'builder.editor.folder': 'scenarios/{folder}',
  'builder.editor.loading': 'Loading scenario…',
  'builder.editor.notFound.title': 'Scenario not found',
  'builder.editor.notFound.body': "There's no folder with this id in scenarios/. Go back and pick another one.",
  'builder.editor.invalid.title': "This scenario has a file the app can't read",
  'builder.editor.invalid.body':
    "{reason}. Fix the file on disk and reload — the builder won't overwrite what it can't read.",
  'builder.editor.tabs.label': 'Scenario sections',
  'builder.editor.tab.identity': 'Identity',
  'builder.editor.tab.world': 'World',
  'builder.editor.tab.starts': 'Starts',
  'builder.editor.tab.characters': 'Characters',
  'builder.editor.tab.media': 'Media',
  'builder.editor.tab.dirty': 'has unsaved changes',
  'builder.editor.tab.invalid': 'has a field to fix',
  'builder.editor.dirty': 'Unsaved changes',
  'builder.editor.clean': 'Everything saved',
  'builder.editor.previewToggle.show': 'Show preview',
  'builder.editor.previewToggle.hide': 'Hide preview',
  'builder.editor.previewClose': 'Close preview',
  'builder.editor.save': 'Save',
  'builder.editor.saving': 'Saving…',
  'builder.editor.saved': 'Saved to scenarios/{folder}',
  'builder.editor.saveShortcut': 'Ctrl+S saves',
  'builder.editor.save.error.title': "Couldn't save",
  'builder.editor.save.error.body': 'Part of the files may have been written. Reload from disk before trying again.',
  'builder.editor.save.error.disabled.title': 'Saving is turned off',
  'builder.editor.save.error.disabled.body':
    'The builder flag is off in ~/.ooc-local/config.yaml. Turn it on to write to disk again.',
  'builder.editor.save.error.validationOne': '1 field needs fixing before saving.',
  'builder.editor.save.error.validationOther': '{count} fields need fixing before saving.',
  'builder.editor.save.error.conflict.title': 'The files changed on disk',
  'builder.editor.save.error.conflict.body':
    "scenarios/{folder} was edited outside the app after you opened it. Reload to take the disk version, or overwrite to keep what's on this screen.",
  'builder.editor.conflict.reload': 'Reload and lose my edits',
  'builder.editor.conflict.overwrite': 'Overwrite the files',
  'builder.editor.reload': 'Reload from disk',
  'builder.editor.reload.confirmTitle': 'Discard your unsaved changes?',
  'builder.editor.reload.confirmBody': 'Reloading reads the files again and throws away what you edited here.',
  'builder.editor.reload.confirmSubmit': 'Reload and discard',
  'builder.editor.reloaded': 'Reloaded from disk',
  'builder.editor.leave.title': 'Leave without saving?',
  'builder.editor.leave.body': '{scenario} has unsaved changes. They only exist in this tab.',
  'builder.editor.leave.stay': 'Keep editing',
  'builder.editor.leave.saveAndLeave': 'Save and leave',
  'builder.editor.leave.discard': 'Leave and discard',
  'builder.editor.validation.summaryTitle': 'Fix these before saving',
  'builder.editor.validation.jump': 'Go to {field}',

  // Builder preview
  'builder.preview.regionLabel': 'Playable preview',
  'builder.preview.heading': 'Preview',
  'builder.preview.ephemeralHint': "Throwaway session: nothing here is saved to your sessions.",
  'builder.preview.idle.title': 'Preview not running',
  'builder.preview.idle.body': 'Start it to play the scenario as it is on disk right now.',
  'builder.preview.start': 'Start the preview',
  'builder.preview.starting': 'Starting the preview…',
  'builder.preview.start.error': "Couldn't start the preview. The scenario files weren't touched — try again.",
  'builder.preview.startLabel': 'Start',
  'builder.preview.startUnsaved': "Save first — this start doesn't exist on disk yet.",
  'builder.preview.stale': "The preview plays what's on disk. Your unsaved edits aren't in it.",
  'builder.preview.outdated': 'The files changed. Restart the preview to play the new version.',
  'builder.preview.saveAndRestart': 'Save and restart',
  'builder.preview.restart': 'Restart',
  'builder.preview.restart.title': 'Restart the preview?',
  'builder.preview.restart.body': 'The {count} turns played here are discarded. They were never saved anyway.',
  'builder.preview.restart.submit': 'Restart',
  'builder.preview.restarted': 'Preview restarted',
  'builder.preview.switchStart.title': 'Switch to the start {name}?',
  'builder.preview.switchStart.body': 'The preview restarts and the turns played here are discarded.',
  'builder.preview.switchStart.submit': 'Switch start',
  'builder.preview.invalid.title': "Can't play this scenario yet",
  'builder.preview.invalid.body': '{reason}. Fix it and the preview starts.',

  // Builder field patterns (shared by identity, world, starts and characters tabs)
  'builder.field.required': 'This field is required.',
  'builder.field.tooLong': 'Too long — {max} characters max.',
  'builder.field.counter': '{count}/{max}',
  'builder.field.slugInvalid': 'Use only lowercase letters, numbers and hyphens.',
  'builder.field.slugTaken': '{slug} is already used in this scenario.',
  'builder.detail.selected': 'Editing {name}',
  'builder.field.label.starts': 'Starts',
  'builder.field.label.defaultStart': 'Default start',
  'builder.field.label.startId': 'Start id',
  'builder.field.label.startCharacters': 'Start characters',
  'builder.field.label.characterId': 'Character id',
  'builder.field.label.characters': 'Characters',
  'builder.field.time.invalid': 'Use 24h time, HH:MM.',
  'builder.field.weather.invalid': 'Pick one of the seven weather options.',

  // Structural validation messages (validateDraft)
  'builder.validate.startsRequired': 'At least one start is required.',
  'builder.validate.defaultStartMissing': 'Default start "{id}" was not found among the starts.',
  'builder.validate.startUnknownCharacter': 'Start "{start}" references unknown character "{character}".',

  // Media errors (shared by identity, media/sprites and media/backgrounds tabs)
  'builder.media.error.type': 'Only PNG, JPEG and WebP images.',
  'builder.media.error.size': 'Image is over {max} MB. Shrink it and try again.',
  'builder.media.error.write': "The file wasn't written. Check that the media folder is writable.",
  'builder.media.error.removeFailed': "The file wasn't removed. It's still on disk.",
  'builder.media.error.disabled': 'Writing is turned off: the builder flag is off in ~/.ooc-local/config.yaml.',
  'builder.media.error.invalidKey': 'Character or emotion name must be a lowercase slug (letters, numbers, hyphens).',

  // Builder editor identity tab
  'builder.identity.heading': 'Identity',
  'builder.identity.name': 'Name',
  'builder.identity.tagline': 'Tagline',
  'builder.identity.tagline.hint': 'One line, shown next to the scenario name.',
  'builder.identity.description': 'Description',
  'builder.identity.description.hint': 'Markdown. Shown to the player before starting.',
  'builder.identity.tags': 'Tags',
  'builder.identity.tags.hint': 'Enter or comma adds a tag.',
  'builder.identity.tags.empty': 'No tags yet.',
  'builder.identity.tags.remove': 'Remove tag {tag}',
  'builder.identity.tags.duplicate': '{tag} is already in the list.',
  'builder.identity.tags.max': 'Up to 12 tags.',
  'builder.identity.locale': 'Scenario language',
  'builder.identity.locale.hint': 'Sets the language of the system prompts, not of this interface.',
  'builder.identity.cover.legend': 'Cover',
  'builder.identity.cover.hint': 'Saved to media/cover as soon as you upload it.',
  'builder.identity.cover.empty': 'No cover yet',
  'builder.identity.cover.upload': 'Upload a cover',
  'builder.identity.cover.replace': 'Replace the cover',
  'builder.identity.cover.remove': 'Remove the cover',
  'builder.identity.cover.uploading': 'Uploading the cover…',
  'builder.identity.cover.error': "The cover wasn't saved. Try again.",
  'builder.identity.cover.alt': 'Cover of {scenario}',

  'builder.world.heading': 'World',
  'builder.world.mode.label': 'How you write the world',
  'builder.world.mode.guided': 'Guided fields',
  'builder.world.mode.custom': 'Custom prompt',
  'builder.world.universe': 'Universe',
  'builder.world.universe.hint': 'Where and when the story happens.',
  'builder.world.tone': 'Tone and narration style',
  'builder.world.tone.hint': 'How the narrator writes: pacing, register, what it avoids.',
  'builder.world.rules': 'World rules',
  'builder.world.rules.hint': "What is possible here and what isn't.",
  'builder.world.lore.legend': 'Lore blocks',
  'builder.world.lore.hint':
    'One block per chunk of world worth its own heading: factions, places, history. Each block becomes a heading in world.md.',
  'builder.world.lore.empty': 'No lore blocks yet. Add one for each piece of the world the narrator should always know.',
  'builder.world.lore.add': 'Add lore block',
  'builder.world.lore.titleLabel': 'Block {index} title',
  'builder.world.lore.title.hint': 'Becomes a heading in world.md.',
  'builder.world.lore.bodyLabel': 'Block {index} text',
  'builder.world.lore.remove': 'Remove lore block {index}',
  'builder.world.lore.added': 'Lore block {index} added',
  'builder.world.lore.removed': 'Lore block {index} removed',
  'builder.world.lore.title.required': 'Every lore block needs a title.',
  'builder.world.lore.title.reserved': '{title} is one of the guided fields above — pick another title.',
  'builder.world.lore.title.duplicate': 'Another block already uses {title}.',
  'builder.world.guided.movedHint':
    'Conflict and mission moved: each start has its own now, so one world can hold many stories.',
  'builder.world.guided.goToStarts': 'Open the Starts tab',
  'builder.world.custom.label': 'Narrator prompt',
  'builder.world.custom.hint': 'The whole narrator prompt, in markdown. Saved as world.md.',
  'builder.world.variables.title': 'Available variables',
  'builder.world.variables.insert': 'Insert {name}',
  'builder.world.variables.player': "The player's name.",
  'builder.world.variables.start': 'The name of the start being played.',
  'builder.world.variables.scenario': 'The scenario name.',
  'builder.world.variables.unknown': "{name} isn't a known variable — it will stay as literal text.",
  'builder.world.variables.unbalanced': 'An opening {{ has no closing }} on the same line.',
  'builder.world.mode.fallback.title': 'world.md was written by hand',
  'builder.world.mode.fallback.body':
    "This file doesn't fit the guided layout, so it opened in custom mode. Nothing was lost.",
  'builder.world.mode.fallback.keepCustom': 'Keep it custom',
  'builder.world.mode.switchToCustom': 'The guided fields were merged into the text below.',
  'builder.world.mode.switchToGuidedTitle': 'Go back to guided fields?',
  'builder.world.mode.switchToGuidedBody': "Anything that doesn't fit the guided headings is dropped.",
  'builder.world.mode.switchToGuidedSubmit': 'Use guided fields',

  'builder.starts.heading': 'Starts',
  'builder.starts.listLabel': 'Starts in this scenario',
  'builder.starts.create': 'New start',
  'builder.starts.create.title': 'New start',
  'builder.starts.create.idLabel': 'File name',
  'builder.starts.create.idHint': 'Becomes starts/{id}.yaml.',
  'builder.starts.create.submit': 'Create start',
  'builder.starts.defaultBadge': 'default',
  'builder.starts.defaultToggle': 'Use this start by default',
  'builder.starts.name': 'Name',
  'builder.starts.prologue': 'Prologue',
  'builder.starts.prologue.hint': 'The first text the player reads.',
  'builder.starts.openingScene': 'Opening scene',
  'builder.starts.openingScene.hint': 'Goes to the narrator only — the player never sees it.',
  'builder.starts.conflict': 'Conflict',
  'builder.starts.conflict.hint':
    'The conflict of this start. Optional, and it goes to the narrator only — the player never sees it.',
  'builder.starts.mission': 'Player mission',
  'builder.starts.mission.hint':
    'What the player is chasing in this start. Optional, and it goes to the narrator only — the player never sees it.',
  'builder.starts.playGuide': 'Play guide',
  'builder.starts.playGuide.hint': "Author's note shown to the player, kept out of the prompt.",
  'builder.starts.suggestions.legend': 'Opening suggestions',
  'builder.starts.suggestions.item': 'Suggestion {index}',
  'builder.starts.suggestions.add': 'Add a suggestion',
  'builder.starts.suggestions.remove': 'Remove suggestion {index}',
  'builder.starts.suggestions.max': 'Up to 3 suggestions.',
  'builder.starts.hud.legend': 'Opening HUD',
  'builder.starts.hud.location': 'Location',
  'builder.starts.hud.time': 'Time',
  'builder.starts.hud.weather': 'Weather',
  'builder.starts.cast.legend': 'Characters on scene',
  'builder.starts.cast.all': 'Whole cast in scene',
  'builder.starts.cast.custom': 'Choose who starts in scene',
  'builder.starts.cast.hint': 'None checked means the scene starts with no NPCs.',
  'builder.starts.cast.empty': 'No characters yet — create one in the Characters tab.',
  'builder.starts.delete': 'Delete start',
  'builder.starts.delete.title': 'Delete the start {name}?',
  'builder.starts.delete.body': 'starts/{id}.yaml is removed when you save.',
  'builder.starts.delete.lastDisabled': 'A scenario needs at least one start.',
  'builder.starts.delete.defaultMoved': '{name} is the default start now.',
  'builder.starts.itemInvalid': 'has a field to fix',

  // Builder characters tab
  'builder.characters.heading': 'Characters',
  'builder.characters.listLabel': 'Characters in this scenario',
  'builder.characters.create': 'New character',
  'builder.characters.create.title': 'New character',
  'builder.characters.create.idLabel': 'File name',
  'builder.characters.create.idHint': 'Becomes characters/{id}.yaml.',
  'builder.characters.create.submit': 'Create character',
  'builder.characters.empty.title': 'No characters yet',
  'builder.characters.empty.body': 'A scenario needs at least one character to be playable. Create the first one.',
  'builder.characters.name': 'Name',
  'builder.characters.role': 'Role',
  'builder.characters.role.hint': 'One line: who they are in this story.',
  'builder.characters.appearance': 'Appearance',
  'builder.characters.appearance.hint': 'Also the base for the sprite art.',
  'builder.characters.personality': 'Personality',
  'builder.characters.voice': 'Voice',
  'builder.characters.voice.hint': 'How they speak: length, register, tics.',
  'builder.characters.mind.legend': 'Starting mind',
  'builder.characters.mind.hint': 'Where this character starts. The game moves it from here.',
  'builder.characters.mind.feeling': 'Feeling',
  'builder.characters.mind.goal': 'Goal',
  'builder.characters.mind.opinion': 'Opinion of the player',
  'builder.characters.mind.secretPlan': 'Secret plan',
  'builder.characters.sprite': 'Sprite folder',
  'builder.characters.sprite.hint': 'Folder under media/sprites/. Defaults to the file name.',
  'builder.characters.tier': 'Power tier',
  'builder.characters.tier.none': 'No tier',
  'builder.characters.tier.hint': 'Optional strength scale. Tier 1 is the strongest.',
  'builder.characters.tierBadge': 'tier {tier}',
  'builder.characters.powerTiers.legend': 'Power levels',
  'builder.characters.powerTiers.hint': 'Optional. Drag characters into a tier; tier 1 is the strongest.',
  'builder.characters.powerTiers.unranked': 'No tier',
  'builder.characters.powerTiers.tier': 'Tier {tier}',
  'builder.characters.powerTiers.add': 'Add tier',
  'builder.characters.powerTiers.moved': '{name} moved to tier {tier}.',
  'builder.characters.powerTiers.movedOut': '{name} removed from the power scale.',
  'builder.characters.emotions.legend': 'Emotions',
  'builder.characters.emotions.hint': 'Each emotion becomes a sprite slot in the Media tab.',
  'builder.characters.emotions.add': 'Add emotion',
  'builder.characters.emotions.remove': 'Remove the emotion {emotion}',
  'builder.characters.emotions.suggest': 'Suggested emotions',
  'builder.characters.emotions.max': 'Up to {max} emotions per character, on top of default.',
  'builder.characters.emotions.defaultLocked': "default always exists — it's the fallback sprite.",
  'builder.characters.emotions.hasAsset': 'If {emotion} has an uploaded sprite, the file stays on disk — it just leaves the grid.',
  'builder.characters.delete': 'Delete character',
  'builder.characters.delete.title': 'Delete {name}?',
  'builder.characters.delete.body': 'characters/{id}.yaml is removed when you save. The sprites in media/sprites/{sprite}/ stay on disk.',
  'builder.characters.delete.castUpdated': '{name} was also removed from these starts: {starts}',

  // Builder media tab
  'builder.media.heading': 'Media',
  'builder.media.hint': 'Images are written to disk the moment you upload them, outside the save button.',
  'builder.media.summary': '{filled} of {total} slots filled',
  'builder.media.empty.title': 'No images yet',
  'builder.media.empty.body': 'The game is text-first: a sprite or background tag with no image is simply ignored. Upload whenever you want.',
  'builder.media.sprites.heading': 'Sprites',
  'builder.media.sprites.folder': 'media/sprites/{folder}/',
  'builder.media.sprites.empty.title': 'No characters to give sprites to',
  'builder.media.sprites.empty.body': 'Create a character first — the sprite grid comes from the emotions declared there.',
  'builder.media.sprites.addEmotions': 'Only default here. Declare more emotions in the Characters tab to get more slots.',
  'builder.media.cell.empty': 'Empty',
  'builder.media.cell.emptyDefault': 'Empty — without default this character shows no sprite at all.',
  'builder.media.cell.uploading': 'Uploading…',
  'builder.media.cell.removing': 'Removing…',
  'builder.media.cell.upload': 'Upload an image',
  'builder.media.cell.replace': 'Replace the image',
  'builder.media.sprite.alt': '{character}, {emotion}',
  'builder.media.sprite.upload': 'Upload the {emotion} sprite for {character}',
  'builder.media.sprite.remove': 'Remove the {emotion} sprite of {character}',
  'builder.media.uploaded': '{name} uploaded',
  'builder.media.replaced': '{name} replaced',
  'builder.media.removed': '{name} removed',
  'builder.media.remove.title': 'Remove this image?',
  'builder.media.remove.body': "{path} is deleted from disk. There's no undo.",
  'builder.media.sprites.orphans.title': 'Files with no matching emotion',
  'builder.media.sprites.orphans.body':
    "These images are in the folder but the character doesn't declare the emotion. The game never shows them.",
  'builder.media.sprites.orphans.declare': 'Declare {emotion}',
  'builder.media.sprites.orphans.folderTitle': 'Folders with no character',
  'builder.media.sprites.orphans.removeFile': 'Remove the {emotion} file from folder {folder}',
  'builder.media.backgrounds.heading': 'Backgrounds',
  'builder.media.backgrounds.add': 'Add a location',
  'builder.media.backgrounds.addLabel': 'Location key',
  'builder.media.backgrounds.addHint': 'Becomes media/backgrounds/{slug}.png and matches [BG:{slug}].',
  'builder.media.backgrounds.removeSlot': 'Remove the empty slot {location}',
  'builder.media.bg.alt': 'Background of {location}',
  'builder.media.bg.upload': 'Upload the background for {location}',
  'builder.media.bg.remove': 'Remove the background of {location}',
  'builder.media.bg.fromStart': 'Location of the start {start}',

  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Loading session…',
  'game.back': 'Back to sessions',
  'game.prologue.label': 'Prologue',
  'game.empty.hint': 'Your turn. Type what you do or say.',
  'game.input.label': 'Your action',
  'game.input.placeholder': 'What do you do?',
  'game.input.send': 'Send',
  'game.input.sending': 'Narrating…',
  'game.input.hint': 'Enter sends · Shift+Enter for a new line',
  'game.turn.playerLabel': 'You',
  'game.turn.narratorLabel': 'Narrator',
  'game.turn.thinking': 'The narrator is writing…',
  'game.turn.done': 'Turn {index} done',
  'game.turn.partial': 'Incomplete turn',
  'game.turn.error': 'The turn stopped halfway',
  'game.turn.errorBody': "The narrator didn't finish. Your message was kept — send it again.",
  'game.scrollToLatest': 'Jump to latest',
  'game.notFound.title': 'Session not found',
  'game.notFound.body': "This session doesn't exist anymore. Go back and pick another one.",
  'game.sprite.alt': '{character}, {emotion}',
  'game.stage.hide': 'Hide the artwork',
  'game.stage.show': 'Show the artwork',
  'game.scene.announce': 'Scene: {background}. On screen: {characters}.',
  'game.scene.announceBackground': 'Scene: {background}.',
  'game.scene.announceCharacters': 'On screen: {characters}.',
  'game.scene.characterEmotion': '{character} ({emotion})',
  'game.scene.empty': 'no one',
  'game.cast.label': 'In scene',
  'game.cast.empty': 'No one',
  'game.cast.unavailable': 'Not known yet',
  'game.cast.announce': 'Now in scene: {characters}.',
  'game.cast.regionLabel': 'Characters in scene',

  // HUD
  'hud.turn': 'Turn',
  'hud.location': 'Location',
  'hud.time': 'Time',
  'hud.weather': 'Weather',
  'hud.placeholder': '—',
  'hud.unavailable': 'Not tracked yet',
  'hud.stale': 'Showing the last known state',
  'hud.announce': 'Turn {turn}, {location}, {time}, {weather}',
  'hud.weather.clear': 'Clear',
  'hud.weather.cloudy': 'Cloudy',
  'hud.weather.rain': 'Rain',
  'hud.weather.storm': 'Storm',
  'hud.weather.snow': 'Snow',
  'hud.weather.fog': 'Fog',
  'hud.weather.night': 'Night',
  'hud.weather.unknown': 'Unknown',

  // Turn text
  'turnText.speakerLabel': '{name} says',
  'turnText.narrationLabel': 'Narration',
  'turnText.rawFallback': 'Shown as the narrator wrote it',
} as const

export type StringKey = keyof typeof en

const ptBr: Record<StringKey, string> = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Pular para o conteúdo',
  'common.retry': 'Tentar de novo',
  'common.cancel': 'Cancelar',
  'common.back': 'Voltar',
  'common.loading': 'Carregando…',
  'common.details': 'Detalhes técnicos',
  'common.save': 'Salvar',
  'common.delete': 'Deletar',
  'common.discard': 'Descartar',
  'common.close': 'Fechar',
  'common.remove': 'Remover',
  'common.add': 'Adicionar',
  'common.reload': 'Recarregar do disco',
  'common.optional': 'opcional',
  'error.offline.title': 'Não consegui falar com o servidor local',
  'error.offline.body': 'O backend em :8000 não respondeu. Confira se o `npm run dev` está rodando e tente de novo.',
  'error.chatDisabled.title': 'O chat está desligado',
  'error.chatDisabled.body': 'A flag `chat` está desligada em ~/.ooc-local/config.yaml. Ligue e reinicie o servidor.',
  'error.unexpected.title': 'Alguma coisa quebrou nesta tela',
  'error.unexpected.body': 'A ação não terminou. Tente de novo; se repetir, olhe o log do servidor.',

  // Session list
  'sessions.heading': 'Suas sessões',
  'sessions.loading': 'Carregando sessões…',
  'sessions.empty.title': 'Nenhuma sessão ainda',
  'sessions.empty.body': 'Escolha um cenário acima e comece sua primeira sessão.',
  'sessions.error.title': 'Não consegui carregar suas sessões',
  'sessions.error.body': 'A lista de sessões não voltou do servidor. Suas sessões salvas estão intactas.',
  'sessions.item.turnsZero': 'Não começou',
  'sessions.item.turnsOne': '1 turno',
  'sessions.item.turnsOther': '{count} turnos',
  'sessions.item.meta': '{turns} · jogada {when}',
  'sessions.item.open': 'Continuar {scenario}',
  'sessions.new.heading': 'Nova sessão',
  'sessions.new.scenarioLabel': 'Cenário',
  'sessions.new.submit': 'Começar sessão',
  'sessions.new.submitting': 'Começando…',
  'sessions.new.error': 'Não consegui começar a sessão. Nada foi salvo — tente de novo.',
  'sessions.new.scenariosError': 'Não consegui carregar os cenários',
  'sessions.builderLink': 'Abrir o builder',

  // Builder list
  'builder.documentTitle': 'Builder — ooc-local',
  'builder.list.heading': 'Seus cenários',
  'builder.list.back': 'Voltar para as sessões',
  'builder.list.loading': 'Carregando cenários…',
  'builder.list.empty.title': 'Nenhum cenário ainda',
  'builder.list.empty.body': 'Um cenário é uma pasta em scenarios/. Crie um aqui, ou solte uma pasta lá e recarregue.',
  'builder.list.error.title': 'Não consegui carregar seus cenários',
  'builder.list.error.body': 'A lista de pastas não voltou do servidor. Nada no disco foi alterado.',
  'builder.list.reload': 'Recarregar do disco',
  'builder.list.reloaded': 'Lista de cenários recarregada do disco',
  'builder.list.item.meta': '{starts} · {characters}',
  'builder.list.item.startsOne': '1 start',
  'builder.list.item.startsOther': '{count} starts',
  'builder.list.item.charactersZero': 'sem personagens',
  'builder.list.item.charactersOne': '1 personagem',
  'builder.list.item.charactersOther': '{count} personagens',
  'builder.list.item.edit': 'Editar {scenario}',
  'builder.list.item.broken': 'Não dá para abrir esta pasta',
  'builder.list.item.brokenBody':
    '{reason}. Conserte o arquivo no disco e recarregue — o builder não sobrescreve o que não consegue ler.',
  'builder.list.item.reasonUnknown': 'Arquivo ilegível',
  'builder.list.item.coverAlt': 'Capa de {scenario}',
  'builder.create.locale.en': 'Inglês',
  'builder.create.locale.ptBr': 'Português (Brasil)',
  'builder.list.empty.action': 'Criar um cenário',
  'builder.create.heading': 'Novo cenário',
  'builder.create.nameLabel': 'Nome',
  'builder.create.namePlaceholder': 'O nome que o jogador vê',
  'builder.create.folderLabel': 'Pasta',
  'builder.create.folderHint': 'Nome da pasta dentro de scenarios/. Letras minúsculas, números e hífens.',
  'builder.create.localeLabel': 'Idioma do cenário',
  'builder.create.submit': 'Criar cenário',
  'builder.create.submitting': 'Criando…',
  'builder.create.error.nameRequired': 'Dê um nome ao cenário.',
  'builder.create.error.invalidFolder': 'Use só letras minúsculas, números e hífens.',
  'builder.create.error.duplicate': 'A pasta {folder} já existe. Escolha outra.',
  'builder.create.error.failed': 'Não consegui criar o cenário. Nada foi escrito no disco — tente de novo.',
  'builder.create.success': 'Cenário {name} criado',
  'builder.duplicate.action': 'Duplicar',
  'builder.duplicate.title': 'Duplicar {scenario}',
  'builder.duplicate.body': 'Copia a pasta inteira, mídia incluída.',
  'builder.duplicate.folderLabel': 'Nova pasta',
  'builder.duplicate.submit': 'Duplicar',
  'builder.duplicate.submitting': 'Duplicando…',
  'builder.duplicate.success': '{scenario} duplicado em {folder}',
  'builder.duplicate.error': 'Não consegui duplicar. A pasta original não foi tocada — tente de novo.',
  'builder.delete.action': 'Deletar',
  'builder.delete.title': 'Deletar {scenario}?',
  'builder.delete.body':
    'A pasta scenarios/{folder} inteira vai embora, mídia incluída. Sessões já jogadas guardam o histórico, mas param de abrir.',
  'builder.delete.confirmLabel': 'Digite {folder} para confirmar',
  'builder.delete.submit': 'Deletar cenário',
  'builder.delete.submitting': 'Deletando…',
  'builder.delete.success': '{scenario} deletado',
  'builder.delete.error':
    'Não consegui deletar a pasta. Nada foi removido — veja se outro programa está com os arquivos abertos.',

  // Builder editor
  'builder.editor.documentTitle': '{scenario} — builder — ooc-local',
  'builder.editor.back': 'Voltar para os cenários',
  'builder.editor.folder': 'scenarios/{folder}',
  'builder.editor.loading': 'Carregando cenário…',
  'builder.editor.notFound.title': 'Cenário não encontrado',
  'builder.editor.notFound.body': 'Não existe pasta com esse id em scenarios/. Volte e escolha outro.',
  'builder.editor.invalid.title': 'Este cenário tem um arquivo que o app não consegue ler',
  'builder.editor.invalid.body':
    '{reason}. Conserte o arquivo no disco e recarregue — o builder não sobrescreve o que não consegue ler.',
  'builder.editor.tabs.label': 'Seções do cenário',
  'builder.editor.tab.identity': 'Identidade',
  'builder.editor.tab.world': 'Mundo',
  'builder.editor.tab.starts': 'Starts',
  'builder.editor.tab.characters': 'Personagens',
  'builder.editor.tab.media': 'Mídia',
  'builder.editor.tab.dirty': 'tem mudanças não salvas',
  'builder.editor.tab.invalid': 'tem campo para consertar',
  'builder.editor.dirty': 'Mudanças não salvas',
  'builder.editor.clean': 'Tudo salvo',
  'builder.editor.previewToggle.show': 'Mostrar preview',
  'builder.editor.previewToggle.hide': 'Esconder preview',
  'builder.editor.previewClose': 'Fechar preview',
  'builder.editor.save': 'Salvar',
  'builder.editor.saving': 'Salvando…',
  'builder.editor.saved': 'Salvo em scenarios/{folder}',
  'builder.editor.saveShortcut': 'Ctrl+S salva',
  'builder.editor.save.error.title': 'Não consegui salvar',
  'builder.editor.save.error.body': 'Parte dos arquivos pode ter sido escrita. Recarregue do disco antes de tentar de novo.',
  'builder.editor.save.error.disabled.title': 'Salvar está desligado',
  'builder.editor.save.error.disabled.body':
    'A flag builder está desligada em ~/.ooc-local/config.yaml. Ligue de novo para gravar no disco.',
  'builder.editor.save.error.validationOne': '1 campo precisa de conserto antes de salvar.',
  'builder.editor.save.error.validationOther': '{count} campos precisam de conserto antes de salvar.',
  'builder.editor.save.error.conflict.title': 'Os arquivos mudaram no disco',
  'builder.editor.save.error.conflict.body':
    "scenarios/{folder} foi editado fora do app depois que você abriu. Recarregue para ficar com a versão do disco, ou sobrescreva para manter o que está nesta tela.",
  'builder.editor.conflict.reload': 'Recarregar e perder minhas edições',
  'builder.editor.conflict.overwrite': 'Sobrescrever os arquivos',
  'builder.editor.reload': 'Recarregar do disco',
  'builder.editor.reload.confirmTitle': 'Descartar suas mudanças não salvas?',
  'builder.editor.reload.confirmBody': 'Recarregar lê os arquivos de novo e joga fora o que você editou aqui.',
  'builder.editor.reload.confirmSubmit': 'Recarregar e descartar',
  'builder.editor.reloaded': 'Recarregado do disco',
  'builder.editor.leave.title': 'Sair sem salvar?',
  'builder.editor.leave.body': '{scenario} tem mudanças não salvas. Elas só existem nesta aba.',
  'builder.editor.leave.stay': 'Continuar editando',
  'builder.editor.leave.saveAndLeave': 'Salvar e sair',
  'builder.editor.leave.discard': 'Sair e descartar',
  'builder.editor.validation.summaryTitle': 'Conserte isto antes de salvar',
  'builder.editor.validation.jump': 'Ir para {field}',

  // Builder preview
  'builder.preview.regionLabel': 'Preview jogável',
  'builder.preview.heading': 'Preview',
  'builder.preview.ephemeralHint': 'Sessão descartável: nada aqui é salvo nas suas sessões.',
  'builder.preview.idle.title': 'Preview parado',
  'builder.preview.idle.body': 'Inicie para jogar o cenário como ele está no disco agora.',
  'builder.preview.start': 'Iniciar o preview',
  'builder.preview.starting': 'Iniciando o preview…',
  'builder.preview.start.error': 'Não consegui iniciar o preview. Os arquivos do cenário não foram tocados — tente de novo.',
  'builder.preview.startLabel': 'Start',
  'builder.preview.startUnsaved': 'Salve antes — este start ainda não existe no disco.',
  'builder.preview.stale': 'O preview joga o que está no disco. Suas edições não salvas não estão nele.',
  'builder.preview.outdated': 'Os arquivos mudaram. Reinicie o preview para jogar a versão nova.',
  'builder.preview.saveAndRestart': 'Salvar e reiniciar',
  'builder.preview.restart': 'Reiniciar',
  'builder.preview.restart.title': 'Reiniciar o preview?',
  'builder.preview.restart.body': 'Os {count} turnos jogados aqui são descartados. Eles nunca foram salvos mesmo.',
  'builder.preview.restart.submit': 'Reiniciar',
  'builder.preview.restarted': 'Preview reiniciado',
  'builder.preview.switchStart.title': 'Trocar para o start {name}?',
  'builder.preview.switchStart.body': 'O preview reinicia e os turnos jogados aqui são descartados.',
  'builder.preview.switchStart.submit': 'Trocar de start',
  'builder.preview.invalid.title': 'Ainda não dá para jogar este cenário',
  'builder.preview.invalid.body': '{reason}. Conserte e o preview inicia.',

  // Builder field patterns (shared by identity, world, starts and characters tabs)
  'builder.field.required': 'Este campo é obrigatório.',
  'builder.field.tooLong': 'Longo demais — máximo de {max} caracteres.',
  'builder.field.counter': '{count}/{max}',
  'builder.field.slugInvalid': 'Use só letras minúsculas, números e hífens.',
  'builder.field.slugTaken': '{slug} já está em uso neste cenário.',
  'builder.detail.selected': 'Editando {name}',
  'builder.field.label.starts': 'Starts',
  'builder.field.label.defaultStart': 'Início padrão',
  'builder.field.label.startId': 'Id do start',
  'builder.field.label.startCharacters': 'Personagens do start',
  'builder.field.label.characterId': 'Id do personagem',
  'builder.field.label.characters': 'Personagens',
  'builder.field.time.invalid': 'Use hora no formato 24h, HH:MM.',
  'builder.field.weather.invalid': 'Escolha uma das sete opções de clima.',

  // Structural validation messages (validateDraft)
  'builder.validate.startsRequired': 'É preciso pelo menos um start.',
  'builder.validate.defaultStartMissing': 'O início padrão "{id}" não foi encontrado entre os starts.',
  'builder.validate.startUnknownCharacter': 'O start "{start}" referencia um personagem desconhecido "{character}".',

  // Media errors (shared by identity, media/sprites and media/backgrounds tabs)
  'builder.media.error.type': 'Só imagens PNG, JPEG e WebP.',
  'builder.media.error.size': 'A imagem passa de {max} MB. Reduza e tente de novo.',
  'builder.media.error.write': 'O arquivo não foi escrito. Confira se a pasta media aceita escrita.',
  'builder.media.error.removeFailed': 'O arquivo não foi removido. Ele continua no disco.',
  'builder.media.error.disabled': 'A escrita está desligada: a flag builder está desligada em ~/.ooc-local/config.yaml.',
  'builder.media.error.invalidKey': 'Nome do personagem ou emoção precisa ser um slug minúsculo (letras, números, hífen).',

  // Builder editor identity tab
  'builder.identity.heading': 'Identidade',
  'builder.identity.name': 'Nome',
  'builder.identity.tagline': 'Tagline',
  'builder.identity.tagline.hint': 'Uma linha, mostrada ao lado do nome do cenário.',
  'builder.identity.description': 'Descrição',
  'builder.identity.description.hint': 'Markdown. Mostrada ao jogador antes de começar.',
  'builder.identity.tags': 'Tags',
  'builder.identity.tags.hint': 'Enter ou vírgula adiciona uma tag.',
  'builder.identity.tags.empty': 'Nenhuma tag ainda.',
  'builder.identity.tags.remove': 'Remover a tag {tag}',
  'builder.identity.tags.duplicate': '{tag} já está na lista.',
  'builder.identity.tags.max': 'Até 12 tags.',
  'builder.identity.locale': 'Idioma do cenário',
  'builder.identity.locale.hint': 'Define o idioma dos prompts de sistema, não o desta interface.',
  'builder.identity.cover.legend': 'Capa',
  'builder.identity.cover.hint': 'Salva em media/cover assim que você envia.',
  'builder.identity.cover.empty': 'Sem capa ainda',
  'builder.identity.cover.upload': 'Enviar uma capa',
  'builder.identity.cover.replace': 'Trocar a capa',
  'builder.identity.cover.remove': 'Remover a capa',
  'builder.identity.cover.uploading': 'Enviando a capa…',
  'builder.identity.cover.error': 'A capa não foi salva. Tente de novo.',
  'builder.identity.cover.alt': 'Capa de {scenario}',

  'builder.world.heading': 'Mundo',
  'builder.world.mode.label': 'Como você escreve o mundo',
  'builder.world.mode.guided': 'Campos guiados',
  'builder.world.mode.custom': 'Prompt custom',
  'builder.world.universe': 'Universo',
  'builder.world.universe.hint': 'Onde e quando a história acontece.',
  'builder.world.tone': 'Tom e estilo de narração',
  'builder.world.tone.hint': 'Como o narrador escreve: ritmo, registro, o que evita.',
  'builder.world.rules': 'Regras do mundo',
  'builder.world.rules.hint': 'O que é possível aqui e o que não é.',
  'builder.world.lore.legend': 'Blocos de lore',
  'builder.world.lore.hint':
    'Um bloco por pedaço de mundo que merece cabeçalho próprio: facções, lugares, história. Cada bloco vira um cabeçalho no world.md.',
  'builder.world.lore.empty':
    'Nenhum bloco de lore ainda. Adicione um para cada pedaço do mundo que o narrador sempre precisa saber.',
  'builder.world.lore.add': 'Adicionar bloco de lore',
  'builder.world.lore.titleLabel': 'Título do bloco {index}',
  'builder.world.lore.title.hint': 'Vira um cabeçalho no world.md.',
  'builder.world.lore.bodyLabel': 'Texto do bloco {index}',
  'builder.world.lore.remove': 'Remover o bloco de lore {index}',
  'builder.world.lore.added': 'Bloco de lore {index} adicionado',
  'builder.world.lore.removed': 'Bloco de lore {index} removido',
  'builder.world.lore.title.required': 'Todo bloco de lore precisa de um título.',
  'builder.world.lore.title.reserved': '{title} é um dos campos guiados aí em cima — escolha outro título.',
  'builder.world.lore.title.duplicate': 'Outro bloco já usa {title}.',
  'builder.world.guided.movedHint':
    'Conflito e missão mudaram de lugar: agora cada start tem os seus, então um mundo só comporta várias histórias.',
  'builder.world.guided.goToStarts': 'Abrir a aba Starts',
  'builder.world.custom.label': 'Prompt do narrador',
  'builder.world.custom.hint': 'O prompt do narrador inteiro, em markdown. Salvo como world.md.',
  'builder.world.variables.title': 'Variáveis disponíveis',
  'builder.world.variables.insert': 'Inserir {name}',
  'builder.world.variables.player': 'O nome do jogador.',
  'builder.world.variables.start': 'O nome do start em jogo.',
  'builder.world.variables.scenario': 'O nome do cenário.',
  'builder.world.variables.unknown': '{name} não é uma variável conhecida — vai ficar como texto literal.',
  'builder.world.variables.unbalanced': 'Um {{ aberto não tem }} fechando na mesma linha.',
  'builder.world.mode.fallback.title': 'O world.md foi escrito à mão',
  'builder.world.mode.fallback.body':
    'Este arquivo não encaixa no formato guiado, então abriu em modo custom. Nada foi perdido.',
  'builder.world.mode.fallback.keepCustom': 'Manter como custom',
  'builder.world.mode.switchToCustom': 'Os campos guiados foram juntados no texto abaixo.',
  'builder.world.mode.switchToGuidedTitle': 'Voltar para os campos guiados?',
  'builder.world.mode.switchToGuidedBody': 'O que não couber nos cabeçalhos guiados é descartado.',
  'builder.world.mode.switchToGuidedSubmit': 'Usar campos guiados',

  'builder.starts.heading': 'Starts',
  'builder.starts.listLabel': 'Starts deste cenário',
  'builder.starts.create': 'Novo start',
  'builder.starts.create.title': 'Novo start',
  'builder.starts.create.idLabel': 'Nome do arquivo',
  'builder.starts.create.idHint': 'Vira starts/{id}.yaml.',
  'builder.starts.create.submit': 'Criar start',
  'builder.starts.defaultBadge': 'padrão',
  'builder.starts.defaultToggle': 'Usar este start por padrão',
  'builder.starts.name': 'Nome',
  'builder.starts.prologue': 'Prólogo',
  'builder.starts.prologue.hint': 'O primeiro texto que o jogador lê.',
  'builder.starts.openingScene': 'Cena inicial',
  'builder.starts.openingScene.hint': 'Vai só para o narrador — o jogador não vê.',
  'builder.starts.conflict': 'Conflito',
  'builder.starts.conflict.hint': 'O conflito deste start. Opcional, e vai só para o narrador — o jogador não vê.',
  'builder.starts.mission': 'Missão do jogador',
  'builder.starts.mission.hint': 'O que o jogador persegue neste start. Opcional, e vai só para o narrador — o jogador não vê.',
  'builder.starts.playGuide': 'Guia de jogo',
  'builder.starts.playGuide.hint': 'Nota do autor mostrada ao jogador, fora do prompt.',
  'builder.starts.suggestions.legend': 'Sugestões iniciais',
  'builder.starts.suggestions.item': 'Sugestão {index}',
  'builder.starts.suggestions.add': 'Adicionar sugestão',
  'builder.starts.suggestions.remove': 'Remover a sugestão {index}',
  'builder.starts.suggestions.max': 'Até 3 sugestões.',
  'builder.starts.hud.legend': 'HUD inicial',
  'builder.starts.hud.location': 'Local',
  'builder.starts.hud.time': 'Hora',
  'builder.starts.hud.weather': 'Clima',
  'builder.starts.cast.legend': 'Personagens em cena',
  'builder.starts.cast.all': 'Elenco inteiro em cena',
  'builder.starts.cast.custom': 'Escolher quem começa em cena',
  'builder.starts.cast.hint': 'Nenhum marcado significa que a cena começa sem NPCs.',
  'builder.starts.cast.empty': 'Nenhum personagem ainda — crie um na aba Personagens.',
  'builder.starts.delete': 'Deletar start',
  'builder.starts.delete.title': 'Deletar o start {name}?',
  'builder.starts.delete.body': 'starts/{id}.yaml é removido quando você salvar.',
  'builder.starts.delete.lastDisabled': 'Um cenário precisa de pelo menos um start.',
  'builder.starts.delete.defaultMoved': '{name} agora é o start padrão.',
  'builder.starts.itemInvalid': 'tem campo para consertar',

  // Builder characters tab
  'builder.characters.heading': 'Personagens',
  'builder.characters.listLabel': 'Personagens deste cenário',
  'builder.characters.create': 'Novo personagem',
  'builder.characters.create.title': 'Novo personagem',
  'builder.characters.create.idLabel': 'Nome do arquivo',
  'builder.characters.create.idHint': 'Vira characters/{id}.yaml.',
  'builder.characters.create.submit': 'Criar personagem',
  'builder.characters.empty.title': 'Nenhum personagem ainda',
  'builder.characters.empty.body': 'Um cenário precisa de pelo menos um personagem para ser jogável. Crie o primeiro.',
  'builder.characters.name': 'Nome',
  'builder.characters.role': 'Papel',
  'builder.characters.role.hint': 'Uma linha: quem essa pessoa é nesta história.',
  'builder.characters.appearance': 'Aparência',
  'builder.characters.appearance.hint': 'Também é a base da arte do sprite.',
  'builder.characters.personality': 'Personalidade',
  'builder.characters.voice': 'Voz',
  'builder.characters.voice.hint': 'Como fala: tamanho, registro, vícios.',
  'builder.characters.mind.legend': 'Mente inicial',
  'builder.characters.mind.hint': 'De onde este personagem parte. O jogo move a partir daqui.',
  'builder.characters.mind.feeling': 'Sentimento',
  'builder.characters.mind.goal': 'Objetivo',
  'builder.characters.mind.opinion': 'Opinião sobre o jogador',
  'builder.characters.mind.secretPlan': 'Plano secreto',
  'builder.characters.sprite': 'Pasta de sprites',
  'builder.characters.sprite.hint': 'Pasta dentro de media/sprites/. O padrão é o nome do arquivo.',
  'builder.characters.tier': 'Tier de poder',
  'builder.characters.tier.none': 'Sem tier',
  'builder.characters.tier.hint': 'Escala de força opcional. Tier 1 é o mais forte.',
  'builder.characters.tierBadge': 'tier {tier}',
  'builder.characters.powerTiers.legend': 'Níveis de poder',
  'builder.characters.powerTiers.hint': 'Opcional. Arraste os personagens para um tier; tier 1 é o mais forte.',
  'builder.characters.powerTiers.unranked': 'Sem tier',
  'builder.characters.powerTiers.tier': 'Tier {tier}',
  'builder.characters.powerTiers.add': 'Adicionar tier',
  'builder.characters.powerTiers.moved': '{name} movido para o tier {tier}.',
  'builder.characters.powerTiers.movedOut': '{name} removido da escala de poder.',
  'builder.characters.emotions.legend': 'Emoções',
  'builder.characters.emotions.hint': 'Cada emoção vira um espaço de sprite na aba Mídia.',
  'builder.characters.emotions.add': 'Adicionar emoção',
  'builder.characters.emotions.remove': 'Remover a emoção {emotion}',
  'builder.characters.emotions.suggest': 'Emoções sugeridas',
  'builder.characters.emotions.max': 'Até {max} emoções por personagem, além do default.',
  'builder.characters.emotions.defaultLocked': 'default sempre existe — é o sprite de fallback.',
  'builder.characters.emotions.hasAsset': 'Se {emotion} tiver sprite enviado, o arquivo fica no disco — só sai do grid.',
  'builder.characters.delete': 'Deletar personagem',
  'builder.characters.delete.title': 'Deletar {name}?',
  'builder.characters.delete.body': 'characters/{id}.yaml é removido quando você salvar. Os sprites em media/sprites/{sprite}/ ficam no disco.',
  'builder.characters.delete.castUpdated': '{name} também saiu destes starts: {starts}',

  // Builder media tab
  'builder.media.heading': 'Mídia',
  'builder.media.hint': 'As imagens são gravadas no disco assim que você envia, fora do botão de salvar.',
  'builder.media.summary': '{filled} de {total} espaços preenchidos',
  'builder.media.empty.title': 'Nenhuma imagem ainda',
  'builder.media.empty.body': 'O jogo é texto-first: tag de sprite ou background sem imagem é simplesmente ignorada. Envie quando quiser.',
  'builder.media.sprites.heading': 'Sprites',
  'builder.media.sprites.folder': 'media/sprites/{folder}/',
  'builder.media.sprites.empty.title': 'Nenhum personagem para receber sprite',
  'builder.media.sprites.empty.body': 'Crie um personagem primeiro — o grid de sprites vem das emoções declaradas lá.',
  'builder.media.sprites.addEmotions': 'Só o default aqui. Declare mais emoções na aba Personagens para ganhar mais espaços.',
  'builder.media.cell.empty': 'Vazio',
  'builder.media.cell.emptyDefault': 'Vazio — sem o default este personagem não mostra sprite nenhum.',
  'builder.media.cell.uploading': 'Enviando…',
  'builder.media.cell.removing': 'Removendo…',
  'builder.media.cell.upload': 'Enviar uma imagem',
  'builder.media.cell.replace': 'Trocar a imagem',
  'builder.media.sprite.alt': '{character}, {emotion}',
  'builder.media.sprite.upload': 'Enviar o sprite {emotion} de {character}',
  'builder.media.sprite.remove': 'Remover o sprite {emotion} de {character}',
  'builder.media.uploaded': '{name} enviado',
  'builder.media.replaced': '{name} trocado',
  'builder.media.removed': '{name} removido',
  'builder.media.remove.title': 'Remover esta imagem?',
  'builder.media.remove.body': '{path} é apagado do disco. Não tem como desfazer.',
  'builder.media.sprites.orphans.title': 'Arquivos sem emoção correspondente',
  'builder.media.sprites.orphans.body':
    'Estas imagens estão na pasta mas o personagem não declara a emoção. O jogo nunca as mostra.',
  'builder.media.sprites.orphans.declare': 'Declarar {emotion}',
  'builder.media.sprites.orphans.folderTitle': 'Pastas sem personagem',
  'builder.media.sprites.orphans.removeFile': 'Remover o arquivo {emotion} da pasta {folder}',
  'builder.media.backgrounds.heading': 'Backgrounds',
  'builder.media.backgrounds.add': 'Adicionar um local',
  'builder.media.backgrounds.addLabel': 'Chave do local',
  'builder.media.backgrounds.addHint': 'Vira media/backgrounds/{slug}.png e casa com [BG:{slug}].',
  'builder.media.backgrounds.removeSlot': 'Remover o espaço vazio {location}',
  'builder.media.bg.alt': 'Background de {location}',
  'builder.media.bg.upload': 'Enviar o background de {location}',
  'builder.media.bg.remove': 'Remover o background de {location}',
  'builder.media.bg.fromStart': 'Local do start {start}',

  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Carregando sessão…',
  'game.back': 'Voltar para as sessões',
  'game.prologue.label': 'Prólogo',
  'game.empty.hint': 'Sua vez. Escreva o que você faz ou fala.',
  'game.input.label': 'Sua ação',
  'game.input.placeholder': 'O que você faz?',
  'game.input.send': 'Enviar',
  'game.input.sending': 'Narrando…',
  'game.input.hint': 'Enter envia · Shift+Enter quebra linha',
  'game.turn.playerLabel': 'Você',
  'game.turn.narratorLabel': 'Narrador',
  'game.turn.thinking': 'O narrador está escrevendo…',
  'game.turn.done': 'Turno {index} pronto',
  'game.turn.partial': 'Turno incompleto',
  'game.turn.error': 'O turno parou no meio',
  'game.turn.errorBody': 'O narrador não terminou. Sua mensagem foi guardada — mande de novo.',
  'game.scrollToLatest': 'Ir para o mais recente',
  'game.notFound.title': 'Sessão não encontrada',
  'game.notFound.body': 'Essa sessão não existe mais. Volte e escolha outra.',
  'game.sprite.alt': '{character}, {emotion}',
  'game.stage.hide': 'Esconder a arte',
  'game.stage.show': 'Mostrar a arte',
  'game.scene.announce': 'Cena: {background}. Em cena: {characters}.',
  'game.scene.announceBackground': 'Cena: {background}.',
  'game.scene.announceCharacters': 'Em cena: {characters}.',
  'game.scene.characterEmotion': '{character} ({emotion})',
  'game.scene.empty': 'ninguém',
  'game.cast.label': 'Em cena',
  'game.cast.empty': 'Ninguém',
  'game.cast.unavailable': 'Ainda não se sabe',
  'game.cast.announce': 'Agora em cena: {characters}.',
  'game.cast.regionLabel': 'Personagens em cena',

  // HUD
  'hud.turn': 'Turno',
  'hud.location': 'Local',
  'hud.time': 'Hora',
  'hud.weather': 'Clima',
  'hud.placeholder': '—',
  'hud.unavailable': 'Ainda não rastreado',
  'hud.stale': 'Mostrando o último estado conhecido',
  'hud.announce': 'Turno {turn}, {location}, {time}, {weather}',
  'hud.weather.clear': 'Limpo',
  'hud.weather.cloudy': 'Nublado',
  'hud.weather.rain': 'Chuva',
  'hud.weather.storm': 'Tempestade',
  'hud.weather.snow': 'Neve',
  'hud.weather.fog': 'Neblina',
  'hud.weather.night': 'Noite',
  'hud.weather.unknown': 'Desconhecido',

  // Turn text
  'turnText.speakerLabel': '{name} diz',
  'turnText.narrationLabel': 'Narração',
  'turnText.rawFallback': 'Mostrado como o narrador escreveu',
}

export const strings = { en, 'pt-br': ptBr }
