const en = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Skip to content',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.loading': 'Loading…',
  'common.details': 'Technical details',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.discard': 'Discard',
  'common.close': 'Close',
  'common.remove': 'Remove',
  'common.add': 'Add',
  'common.reload': 'Reload from disk',
  'common.optional': 'optional',
  'error.offline.title': "Can't reach the local server",
  'error.offline.body': "The backend at :8000 didn't answer. Check that `npm run dev` is running and try again.",
  'error.chatDisabled.title': 'Chat is turned off',
  'error.chatDisabled.body': 'The `chat` flag is off in ~/.ooc-local/config.yaml. Turn it on and restart the server.',
  'error.unexpected.title': 'Something broke on this screen',
  'error.unexpected.body': "The action didn't complete. Try again; if it repeats, check the server log.",

  // Session list
  'sessions.heading': 'Your sessions',
  'sessions.loading': 'Loading sessions…',
  'sessions.empty.title': 'No sessions yet',
  'sessions.empty.body': 'Pick a scenario above and start your first session.',
  'sessions.error.title': "Couldn't load your sessions",
  'sessions.error.body': "The session list didn't come back from the server. Your saved sessions are intact.",
  'sessions.item.turnsZero': 'Not started',
  'sessions.item.turnsOne': '1 turn',
  'sessions.item.turnsOther': '{count} turns',
  'sessions.item.meta': '{turns} · last played {when}',
  'sessions.item.open': 'Continue {scenario}',
  'sessions.new.heading': 'New session',
  'sessions.new.scenarioLabel': 'Scenario',
  'sessions.new.submit': 'Start session',
  'sessions.new.submitting': 'Starting…',
  'sessions.new.error': "Couldn't start the session. Nothing was saved — try again.",
  'sessions.new.scenariosError': "Couldn't load scenarios",
  'sessions.builderLink': 'Open the builder',

  // Builder list
  'builder.documentTitle': 'Builder — ooc-local',
  'builder.list.heading': 'Your scenarios',
  'builder.list.back': 'Back to sessions',
  'builder.list.loading': 'Loading scenarios…',
  'builder.list.empty.title': 'No scenarios yet',
  'builder.list.empty.body':
    'A scenario is a folder in scenarios/. Create one here, or drop a folder there and reload.',
  'builder.list.error.title': "Couldn't load your scenarios",
  'builder.list.error.body': "The folder list didn't come back from the server. Nothing on disk was changed.",
  'builder.list.reload': 'Reload from disk',
  'builder.list.reloaded': 'Scenario list reloaded from disk',
  'builder.list.item.meta': '{starts} · {characters}',
  'builder.list.item.startsOne': '1 start',
  'builder.list.item.startsOther': '{count} starts',
  'builder.list.item.charactersZero': 'no characters',
  'builder.list.item.charactersOne': '1 character',
  'builder.list.item.charactersOther': '{count} characters',
  'builder.list.item.edit': 'Edit {scenario}',
  'builder.list.item.broken': "This folder can't be opened",
  'builder.list.item.brokenBody':
    "{reason}. Fix the file on disk and reload — the builder won't overwrite what it can't read.",
  'builder.list.item.reasonUnknown': 'Unreadable file',
  'builder.list.item.coverAlt': 'Cover of {scenario}',
  'builder.create.locale.en': 'English',
  'builder.create.locale.ptBr': 'Portuguese (Brazil)',

  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Loading session…',
  'game.back': 'Back to sessions',
  'game.prologue.label': 'Prologue',
  'game.empty.hint': 'Your turn. Type what you do or say.',
  'game.input.label': 'Your action',
  'game.input.placeholder': 'What do you do?',
  'game.input.send': 'Send',
  'game.input.sending': 'Narrating…',
  'game.input.hint': 'Enter sends · Shift+Enter for a new line',
  'game.turn.playerLabel': 'You',
  'game.turn.narratorLabel': 'Narrator',
  'game.turn.thinking': 'The narrator is writing…',
  'game.turn.done': 'Turn {index} done',
  'game.turn.partial': 'Incomplete turn',
  'game.turn.error': 'The turn stopped halfway',
  'game.turn.errorBody': "The narrator didn't finish. Your message was kept — send it again.",
  'game.scrollToLatest': 'Jump to latest',
  'game.notFound.title': 'Session not found',
  'game.notFound.body': "This session doesn't exist anymore. Go back and pick another one.",

  // HUD
  'hud.turn': 'Turn',
  'hud.location': 'Location',
  'hud.time': 'Time',
  'hud.weather': 'Weather',
  'hud.placeholder': '—',
  'hud.unavailable': 'Not tracked yet',
  'hud.stale': 'Showing the last known state',
  'hud.announce': 'Turn {turn}, {location}, {time}, {weather}',
  'hud.weather.clear': 'Clear',
  'hud.weather.cloudy': 'Cloudy',
  'hud.weather.rain': 'Rain',
  'hud.weather.storm': 'Storm',
  'hud.weather.snow': 'Snow',
  'hud.weather.fog': 'Fog',
  'hud.weather.night': 'Night',
  'hud.weather.unknown': 'Unknown',

  // Turn text
  'turnText.speakerLabel': '{name} says',
  'turnText.narrationLabel': 'Narration',
  'turnText.rawFallback': 'Shown as the narrator wrote it',
} as const

export type StringKey = keyof typeof en

const ptBr: Record<StringKey, string> = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Pular para o conteúdo',
  'common.retry': 'Tentar de novo',
  'common.cancel': 'Cancelar',
  'common.back': 'Voltar',
  'common.loading': 'Carregando…',
  'common.details': 'Detalhes técnicos',
  'common.save': 'Salvar',
  'common.delete': 'Deletar',
  'common.discard': 'Descartar',
  'common.close': 'Fechar',
  'common.remove': 'Remover',
  'common.add': 'Adicionar',
  'common.reload': 'Recarregar do disco',
  'common.optional': 'opcional',
  'error.offline.title': 'Não consegui falar com o servidor local',
  'error.offline.body': 'O backend em :8000 não respondeu. Confira se o `npm run dev` está rodando e tente de novo.',
  'error.chatDisabled.title': 'O chat está desligado',
  'error.chatDisabled.body': 'A flag `chat` está desligada em ~/.ooc-local/config.yaml. Ligue e reinicie o servidor.',
  'error.unexpected.title': 'Alguma coisa quebrou nesta tela',
  'error.unexpected.body': 'A ação não terminou. Tente de novo; se repetir, olhe o log do servidor.',

  // Session list
  'sessions.heading': 'Suas sessões',
  'sessions.loading': 'Carregando sessões…',
  'sessions.empty.title': 'Nenhuma sessão ainda',
  'sessions.empty.body': 'Escolha um cenário acima e comece sua primeira sessão.',
  'sessions.error.title': 'Não consegui carregar suas sessões',
  'sessions.error.body': 'A lista de sessões não voltou do servidor. Suas sessões salvas estão intactas.',
  'sessions.item.turnsZero': 'Não começou',
  'sessions.item.turnsOne': '1 turno',
  'sessions.item.turnsOther': '{count} turnos',
  'sessions.item.meta': '{turns} · jogada {when}',
  'sessions.item.open': 'Continuar {scenario}',
  'sessions.new.heading': 'Nova sessão',
  'sessions.new.scenarioLabel': 'Cenário',
  'sessions.new.submit': 'Começar sessão',
  'sessions.new.submitting': 'Começando…',
  'sessions.new.error': 'Não consegui começar a sessão. Nada foi salvo — tente de novo.',
  'sessions.new.scenariosError': 'Não consegui carregar os cenários',
  'sessions.builderLink': 'Abrir o builder',

  // Builder list
  'builder.documentTitle': 'Builder — ooc-local',
  'builder.list.heading': 'Seus cenários',
  'builder.list.back': 'Voltar para as sessões',
  'builder.list.loading': 'Carregando cenários…',
  'builder.list.empty.title': 'Nenhum cenário ainda',
  'builder.list.empty.body': 'Um cenário é uma pasta em scenarios/. Crie um aqui, ou solte uma pasta lá e recarregue.',
  'builder.list.error.title': 'Não consegui carregar seus cenários',
  'builder.list.error.body': 'A lista de pastas não voltou do servidor. Nada no disco foi alterado.',
  'builder.list.reload': 'Recarregar do disco',
  'builder.list.reloaded': 'Lista de cenários recarregada do disco',
  'builder.list.item.meta': '{starts} · {characters}',
  'builder.list.item.startsOne': '1 start',
  'builder.list.item.startsOther': '{count} starts',
  'builder.list.item.charactersZero': 'sem personagens',
  'builder.list.item.charactersOne': '1 personagem',
  'builder.list.item.charactersOther': '{count} personagens',
  'builder.list.item.edit': 'Editar {scenario}',
  'builder.list.item.broken': 'Não dá para abrir esta pasta',
  'builder.list.item.brokenBody':
    '{reason}. Conserte o arquivo no disco e recarregue — o builder não sobrescreve o que não consegue ler.',
  'builder.list.item.reasonUnknown': 'Arquivo ilegível',
  'builder.list.item.coverAlt': 'Capa de {scenario}',
  'builder.create.locale.en': 'Inglês',
  'builder.create.locale.ptBr': 'Português (Brasil)',

  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Carregando sessão…',
  'game.back': 'Voltar para as sessões',
  'game.prologue.label': 'Prólogo',
  'game.empty.hint': 'Sua vez. Escreva o que você faz ou fala.',
  'game.input.label': 'Sua ação',
  'game.input.placeholder': 'O que você faz?',
  'game.input.send': 'Enviar',
  'game.input.sending': 'Narrando…',
  'game.input.hint': 'Enter envia · Shift+Enter quebra linha',
  'game.turn.playerLabel': 'Você',
  'game.turn.narratorLabel': 'Narrador',
  'game.turn.thinking': 'O narrador está escrevendo…',
  'game.turn.done': 'Turno {index} pronto',
  'game.turn.partial': 'Turno incompleto',
  'game.turn.error': 'O turno parou no meio',
  'game.turn.errorBody': 'O narrador não terminou. Sua mensagem foi guardada — mande de novo.',
  'game.scrollToLatest': 'Ir para o mais recente',
  'game.notFound.title': 'Sessão não encontrada',
  'game.notFound.body': 'Essa sessão não existe mais. Volte e escolha outra.',

  // HUD
  'hud.turn': 'Turno',
  'hud.location': 'Local',
  'hud.time': 'Hora',
  'hud.weather': 'Clima',
  'hud.placeholder': '—',
  'hud.unavailable': 'Ainda não rastreado',
  'hud.stale': 'Mostrando o último estado conhecido',
  'hud.announce': 'Turno {turn}, {location}, {time}, {weather}',
  'hud.weather.clear': 'Limpo',
  'hud.weather.cloudy': 'Nublado',
  'hud.weather.rain': 'Chuva',
  'hud.weather.storm': 'Tempestade',
  'hud.weather.snow': 'Neve',
  'hud.weather.fog': 'Neblina',
  'hud.weather.night': 'Noite',
  'hud.weather.unknown': 'Desconhecido',

  // Turn text
  'turnText.speakerLabel': '{name} diz',
  'turnText.narrationLabel': 'Narração',
  'turnText.rawFallback': 'Mostrado como o narrador escreveu',
}

export const strings = { en, 'pt-br': ptBr }
