const en = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Skip to content',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.loading': 'Loading…',
  'common.details': 'Technical details',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.discard': 'Discard',
  'common.close': 'Close',
  'common.remove': 'Remove',
  'common.add': 'Add',
  'common.reload': 'Reload from disk',
  'common.optional': 'optional',
  'error.offline.title': "Can't reach the local server",
  'error.offline.body': "The backend at :8000 didn't answer. Check that `npm run dev` is running and try again.",
  'error.chatDisabled.title': 'Chat is turned off',
  'error.chatDisabled.body': 'The `chat` flag is off in ~/.ooc-local/config.yaml. Turn it on and restart the server.',
  'error.unexpected.title': 'Something broke on this screen',
  'error.unexpected.body': "The action didn't complete. Try again; if it repeats, check the server log.",

  // Session list
  'sessions.heading': 'Your sessions',
  'sessions.loading': 'Loading sessions…',
  'sessions.empty.title': 'No sessions yet',
  'sessions.empty.body': 'Pick a scenario above and start your first session.',
  'sessions.error.title': "Couldn't load your sessions",
  'sessions.error.body': "The session list didn't come back from the server. Your saved sessions are intact.",
  'sessions.item.turnsZero': 'Not started',
  'sessions.item.turnsOne': '1 turn',
  'sessions.item.turnsOther': '{count} turns',
  'sessions.item.meta': '{turns} · last played {when}',
  'sessions.item.open': 'Continue {scenario}',
  'sessions.new.heading': 'New session',
  'sessions.new.scenarioLabel': 'Scenario',
  'sessions.new.submit': 'Start session',
  'sessions.new.submitting': 'Starting…',
  'sessions.new.error': "Couldn't start the session. Nothing was saved — try again.",
  'sessions.new.scenariosError': "Couldn't load scenarios",
  'sessions.builderLink': 'Open the builder',

  // Builder list
  'builder.documentTitle': 'Builder — ooc-local',
  'builder.list.heading': 'Your scenarios',
  'builder.list.back': 'Back to sessions',
  'builder.list.loading': 'Loading scenarios…',
  'builder.list.empty.title': 'No scenarios yet',
  'builder.list.empty.body':
    'A scenario is a folder in scenarios/. Create one here, or drop a folder there and reload.',
  'builder.list.error.title': "Couldn't load your scenarios",
  'builder.list.error.body': "The folder list didn't come back from the server. Nothing on disk was changed.",
  'builder.list.reload': 'Reload from disk',
  'builder.list.reloaded': 'Scenario list reloaded from disk',
  'builder.list.item.meta': '{starts} · {characters}',
  'builder.list.item.startsOne': '1 start',
  'builder.list.item.startsOther': '{count} starts',
  'builder.list.item.charactersZero': 'no characters',
  'builder.list.item.charactersOne': '1 character',
  'builder.list.item.charactersOther': '{count} characters',
  'builder.list.item.edit': 'Edit {scenario}',
  'builder.list.item.broken': "This folder can't be opened",
  'builder.list.item.brokenBody':
    "{reason}. Fix the file on disk and reload — the builder won't overwrite what it can't read.",
  'builder.list.item.reasonUnknown': 'Unreadable file',
  'builder.list.item.coverAlt': 'Cover of {scenario}',
  'builder.create.locale.en': 'English',
  'builder.create.locale.ptBr': 'Portuguese (Brazil)',
  'builder.list.empty.action': 'Create a scenario',
  'builder.create.heading': 'New scenario',
  'builder.create.nameLabel': 'Name',
  'builder.create.namePlaceholder': 'The name players see',
  'builder.create.folderLabel': 'Folder',
  'builder.create.folderHint': 'Folder name inside scenarios/. Lowercase letters, numbers and hyphens.',
  'builder.create.localeLabel': 'Scenario language',
  'builder.create.submit': 'Create scenario',
  'builder.create.submitting': 'Creating…',
  'builder.create.error.nameRequired': 'Give the scenario a name.',
  'builder.create.error.invalidFolder': 'Use only lowercase letters, numbers and hyphens.',
  'builder.create.error.duplicate': 'The folder {folder} already exists. Pick another one.',
  'builder.create.error.failed': "Couldn't create the scenario. Nothing was written to disk — try again.",
  'builder.create.success': 'Scenario {name} created',
  'builder.duplicate.action': 'Duplicate',
  'builder.duplicate.title': 'Duplicate {scenario}',
  'builder.duplicate.body': 'Copies the whole folder, media included.',
  'builder.duplicate.folderLabel': 'New folder',
  'builder.duplicate.submit': 'Duplicate',
  'builder.duplicate.submitting': 'Duplicating…',
  'builder.duplicate.success': '{scenario} duplicated into {folder}',
  'builder.duplicate.error': "Couldn't duplicate. The original folder wasn't touched — try again.",
  'builder.delete.action': 'Delete',
  'builder.delete.title': 'Delete {scenario}?',
  'builder.delete.body':
    'The whole scenarios/{folder} folder goes away, media included. Sessions already played keep their history but stop opening.',
  'builder.delete.confirmLabel': 'Type {folder} to confirm',
  'builder.delete.submit': 'Delete scenario',
  'builder.delete.submitting': 'Deleting…',
  'builder.delete.success': '{scenario} deleted',
  'builder.delete.error':
    "Couldn't delete the folder. Nothing was removed — check that no other program has the files open.",

  // Builder editor
  'builder.editor.documentTitle': '{scenario} — builder — ooc-local',
  'builder.editor.back': 'Back to scenarios',
  'builder.editor.folder': 'scenarios/{folder}',
  'builder.editor.loading': 'Loading scenario…',
  'builder.editor.notFound.title': 'Scenario not found',
  'builder.editor.notFound.body': "There's no folder with this id in scenarios/. Go back and pick another one.",
  'builder.editor.invalid.title': "This scenario has a file the app can't read",
  'builder.editor.invalid.body':
    "{reason}. Fix the file on disk and reload — the builder won't overwrite what it can't read.",
  'builder.editor.tabs.label': 'Scenario sections',
  'builder.editor.tab.identity': 'Identity',
  'builder.editor.tab.world': 'World',
  'builder.editor.tab.starts': 'Starts',
  'builder.editor.tab.characters': 'Characters',
  'builder.editor.tab.media': 'Media',
  'builder.editor.tab.dirty': 'has unsaved changes',
  'builder.editor.tab.invalid': 'has a field to fix',
  'builder.editor.dirty': 'Unsaved changes',
  'builder.editor.clean': 'Everything saved',
  'builder.editor.previewToggle.show': 'Show preview',
  'builder.editor.previewToggle.hide': 'Hide preview',
  'builder.editor.save': 'Save',
  'builder.editor.saving': 'Saving…',
  'builder.editor.saved': 'Saved to scenarios/{folder}',
  'builder.editor.saveShortcut': 'Ctrl+S saves',
  'builder.editor.save.error.title': "Couldn't save",
  'builder.editor.save.error.body': 'Part of the files may have been written. Reload from disk before trying again.',
  'builder.editor.save.error.disabled.title': 'Saving is turned off',
  'builder.editor.save.error.disabled.body':
    'The builder flag is off in ~/.ooc-local/config.yaml. Turn it on to write to disk again.',
  'builder.editor.save.error.validationOne': '1 field needs fixing before saving.',
  'builder.editor.save.error.validationOther': '{count} fields need fixing before saving.',
  'builder.editor.save.error.conflict.title': 'The files changed on disk',
  'builder.editor.save.error.conflict.body':
    "scenarios/{folder} was edited outside the app after you opened it. Reload to take the disk version, or overwrite to keep what's on this screen.",
  'builder.editor.conflict.reload': 'Reload and lose my edits',
  'builder.editor.conflict.overwrite': 'Overwrite the files',
  'builder.editor.reload': 'Reload from disk',
  'builder.editor.reload.confirmTitle': 'Discard your unsaved changes?',
  'builder.editor.reload.confirmBody': 'Reloading reads the files again and throws away what you edited here.',
  'builder.editor.reload.confirmSubmit': 'Reload and discard',
  'builder.editor.reloaded': 'Reloaded from disk',
  'builder.editor.leave.title': 'Leave without saving?',
  'builder.editor.leave.body': '{scenario} has unsaved changes. They only exist in this tab.',
  'builder.editor.leave.stay': 'Keep editing',
  'builder.editor.leave.saveAndLeave': 'Save and leave',
  'builder.editor.leave.discard': 'Leave and discard',
  'builder.editor.validation.summaryTitle': 'Fix these before saving',
  'builder.editor.validation.jump': 'Go to {field}',

  // Builder field patterns (shared by identity, world, starts and characters tabs)
  'builder.field.required': 'This field is required.',
  'builder.field.tooLong': 'Too long — {max} characters max.',
  'builder.field.counter': '{count}/{max}',
  'builder.field.slugInvalid': 'Use only lowercase letters, numbers and hyphens.',
  'builder.field.slugTaken': '{slug} is already used in this scenario.',
  'builder.detail.selected': 'Editing {name}',

  // Media errors (shared by identity, media/sprites and media/backgrounds tabs)
  'builder.media.error.type': 'Only PNG, JPEG and WebP images.',
  'builder.media.error.size': 'Image is over {max} MB. Shrink it and try again.',
  'builder.media.error.write': "The file wasn't written. Check that the media folder is writable.",
  'builder.media.error.removeFailed': "The file wasn't removed. It's still on disk.",
  'builder.media.error.disabled': 'Writing is turned off: the builder flag is off in ~/.ooc-local/config.yaml.',

  // Builder editor identity tab
  'builder.identity.heading': 'Identity',
  'builder.identity.name': 'Name',
  'builder.identity.tagline': 'Tagline',
  'builder.identity.tagline.hint': 'One line, shown next to the scenario name.',
  'builder.identity.description': 'Description',
  'builder.identity.description.hint': 'Markdown. Shown to the player before starting.',
  'builder.identity.tags': 'Tags',
  'builder.identity.tags.hint': 'Enter or comma adds a tag.',
  'builder.identity.tags.empty': 'No tags yet.',
  'builder.identity.tags.remove': 'Remove tag {tag}',
  'builder.identity.tags.duplicate': '{tag} is already in the list.',
  'builder.identity.tags.max': 'Up to 12 tags.',
  'builder.identity.locale': 'Scenario language',
  'builder.identity.locale.hint': 'Sets the language of the system prompts, not of this interface.',
  'builder.identity.cover.legend': 'Cover',
  'builder.identity.cover.hint': 'Saved to media/cover as soon as you upload it.',
  'builder.identity.cover.empty': 'No cover yet',
  'builder.identity.cover.upload': 'Upload a cover',
  'builder.identity.cover.replace': 'Replace the cover',
  'builder.identity.cover.remove': 'Remove the cover',
  'builder.identity.cover.uploading': 'Uploading the cover…',
  'builder.identity.cover.error': "The cover wasn't saved. Try again.",
  'builder.identity.cover.alt': 'Cover of {scenario}',

  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Loading session…',
  'game.back': 'Back to sessions',
  'game.prologue.label': 'Prologue',
  'game.empty.hint': 'Your turn. Type what you do or say.',
  'game.input.label': 'Your action',
  'game.input.placeholder': 'What do you do?',
  'game.input.send': 'Send',
  'game.input.sending': 'Narrating…',
  'game.input.hint': 'Enter sends · Shift+Enter for a new line',
  'game.turn.playerLabel': 'You',
  'game.turn.narratorLabel': 'Narrator',
  'game.turn.thinking': 'The narrator is writing…',
  'game.turn.done': 'Turn {index} done',
  'game.turn.partial': 'Incomplete turn',
  'game.turn.error': 'The turn stopped halfway',
  'game.turn.errorBody': "The narrator didn't finish. Your message was kept — send it again.",
  'game.scrollToLatest': 'Jump to latest',
  'game.notFound.title': 'Session not found',
  'game.notFound.body': "This session doesn't exist anymore. Go back and pick another one.",

  // HUD
  'hud.turn': 'Turn',
  'hud.location': 'Location',
  'hud.time': 'Time',
  'hud.weather': 'Weather',
  'hud.placeholder': '—',
  'hud.unavailable': 'Not tracked yet',
  'hud.stale': 'Showing the last known state',
  'hud.announce': 'Turn {turn}, {location}, {time}, {weather}',
  'hud.weather.clear': 'Clear',
  'hud.weather.cloudy': 'Cloudy',
  'hud.weather.rain': 'Rain',
  'hud.weather.storm': 'Storm',
  'hud.weather.snow': 'Snow',
  'hud.weather.fog': 'Fog',
  'hud.weather.night': 'Night',
  'hud.weather.unknown': 'Unknown',

  // Turn text
  'turnText.speakerLabel': '{name} says',
  'turnText.narrationLabel': 'Narration',
  'turnText.rawFallback': 'Shown as the narrator wrote it',
} as const

export type StringKey = keyof typeof en

const ptBr: Record<StringKey, string> = {
  // Shell and common
  'app.title': 'ooc-local',
  'app.skipToContent': 'Pular para o conteúdo',
  'common.retry': 'Tentar de novo',
  'common.cancel': 'Cancelar',
  'common.back': 'Voltar',
  'common.loading': 'Carregando…',
  'common.details': 'Detalhes técnicos',
  'common.save': 'Salvar',
  'common.delete': 'Deletar',
  'common.discard': 'Descartar',
  'common.close': 'Fechar',
  'common.remove': 'Remover',
  'common.add': 'Adicionar',
  'common.reload': 'Recarregar do disco',
  'common.optional': 'opcional',
  'error.offline.title': 'Não consegui falar com o servidor local',
  'error.offline.body': 'O backend em :8000 não respondeu. Confira se o `npm run dev` está rodando e tente de novo.',
  'error.chatDisabled.title': 'O chat está desligado',
  'error.chatDisabled.body': 'A flag `chat` está desligada em ~/.ooc-local/config.yaml. Ligue e reinicie o servidor.',
  'error.unexpected.title': 'Alguma coisa quebrou nesta tela',
  'error.unexpected.body': 'A ação não terminou. Tente de novo; se repetir, olhe o log do servidor.',

  // Session list
  'sessions.heading': 'Suas sessões',
  'sessions.loading': 'Carregando sessões…',
  'sessions.empty.title': 'Nenhuma sessão ainda',
  'sessions.empty.body': 'Escolha um cenário acima e comece sua primeira sessão.',
  'sessions.error.title': 'Não consegui carregar suas sessões',
  'sessions.error.body': 'A lista de sessões não voltou do servidor. Suas sessões salvas estão intactas.',
  'sessions.item.turnsZero': 'Não começou',
  'sessions.item.turnsOne': '1 turno',
  'sessions.item.turnsOther': '{count} turnos',
  'sessions.item.meta': '{turns} · jogada {when}',
  'sessions.item.open': 'Continuar {scenario}',
  'sessions.new.heading': 'Nova sessão',
  'sessions.new.scenarioLabel': 'Cenário',
  'sessions.new.submit': 'Começar sessão',
  'sessions.new.submitting': 'Começando…',
  'sessions.new.error': 'Não consegui começar a sessão. Nada foi salvo — tente de novo.',
  'sessions.new.scenariosError': 'Não consegui carregar os cenários',
  'sessions.builderLink': 'Abrir o builder',

  // Builder list
  'builder.documentTitle': 'Builder — ooc-local',
  'builder.list.heading': 'Seus cenários',
  'builder.list.back': 'Voltar para as sessões',
  'builder.list.loading': 'Carregando cenários…',
  'builder.list.empty.title': 'Nenhum cenário ainda',
  'builder.list.empty.body': 'Um cenário é uma pasta em scenarios/. Crie um aqui, ou solte uma pasta lá e recarregue.',
  'builder.list.error.title': 'Não consegui carregar seus cenários',
  'builder.list.error.body': 'A lista de pastas não voltou do servidor. Nada no disco foi alterado.',
  'builder.list.reload': 'Recarregar do disco',
  'builder.list.reloaded': 'Lista de cenários recarregada do disco',
  'builder.list.item.meta': '{starts} · {characters}',
  'builder.list.item.startsOne': '1 start',
  'builder.list.item.startsOther': '{count} starts',
  'builder.list.item.charactersZero': 'sem personagens',
  'builder.list.item.charactersOne': '1 personagem',
  'builder.list.item.charactersOther': '{count} personagens',
  'builder.list.item.edit': 'Editar {scenario}',
  'builder.list.item.broken': 'Não dá para abrir esta pasta',
  'builder.list.item.brokenBody':
    '{reason}. Conserte o arquivo no disco e recarregue — o builder não sobrescreve o que não consegue ler.',
  'builder.list.item.reasonUnknown': 'Arquivo ilegível',
  'builder.list.item.coverAlt': 'Capa de {scenario}',
  'builder.create.locale.en': 'Inglês',
  'builder.create.locale.ptBr': 'Português (Brasil)',
  'builder.list.empty.action': 'Criar um cenário',
  'builder.create.heading': 'Novo cenário',
  'builder.create.nameLabel': 'Nome',
  'builder.create.namePlaceholder': 'O nome que o jogador vê',
  'builder.create.folderLabel': 'Pasta',
  'builder.create.folderHint': 'Nome da pasta dentro de scenarios/. Letras minúsculas, números e hífens.',
  'builder.create.localeLabel': 'Idioma do cenário',
  'builder.create.submit': 'Criar cenário',
  'builder.create.submitting': 'Criando…',
  'builder.create.error.nameRequired': 'Dê um nome ao cenário.',
  'builder.create.error.invalidFolder': 'Use só letras minúsculas, números e hífens.',
  'builder.create.error.duplicate': 'A pasta {folder} já existe. Escolha outra.',
  'builder.create.error.failed': 'Não consegui criar o cenário. Nada foi escrito no disco — tente de novo.',
  'builder.create.success': 'Cenário {name} criado',
  'builder.duplicate.action': 'Duplicar',
  'builder.duplicate.title': 'Duplicar {scenario}',
  'builder.duplicate.body': 'Copia a pasta inteira, mídia incluída.',
  'builder.duplicate.folderLabel': 'Nova pasta',
  'builder.duplicate.submit': 'Duplicar',
  'builder.duplicate.submitting': 'Duplicando…',
  'builder.duplicate.success': '{scenario} duplicado em {folder}',
  'builder.duplicate.error': 'Não consegui duplicar. A pasta original não foi tocada — tente de novo.',
  'builder.delete.action': 'Deletar',
  'builder.delete.title': 'Deletar {scenario}?',
  'builder.delete.body':
    'A pasta scenarios/{folder} inteira vai embora, mídia incluída. Sessões já jogadas guardam o histórico, mas param de abrir.',
  'builder.delete.confirmLabel': 'Digite {folder} para confirmar',
  'builder.delete.submit': 'Deletar cenário',
  'builder.delete.submitting': 'Deletando…',
  'builder.delete.success': '{scenario} deletado',
  'builder.delete.error':
    'Não consegui deletar a pasta. Nada foi removido — veja se outro programa está com os arquivos abertos.',

  // Builder editor
  'builder.editor.documentTitle': '{scenario} — builder — ooc-local',
  'builder.editor.back': 'Voltar para os cenários',
  'builder.editor.folder': 'scenarios/{folder}',
  'builder.editor.loading': 'Carregando cenário…',
  'builder.editor.notFound.title': 'Cenário não encontrado',
  'builder.editor.notFound.body': 'Não existe pasta com esse id em scenarios/. Volte e escolha outro.',
  'builder.editor.invalid.title': 'Este cenário tem um arquivo que o app não consegue ler',
  'builder.editor.invalid.body':
    '{reason}. Conserte o arquivo no disco e recarregue — o builder não sobrescreve o que não consegue ler.',
  'builder.editor.tabs.label': 'Seções do cenário',
  'builder.editor.tab.identity': 'Identidade',
  'builder.editor.tab.world': 'Mundo',
  'builder.editor.tab.starts': 'Starts',
  'builder.editor.tab.characters': 'Personagens',
  'builder.editor.tab.media': 'Mídia',
  'builder.editor.tab.dirty': 'tem mudanças não salvas',
  'builder.editor.tab.invalid': 'tem campo para consertar',
  'builder.editor.dirty': 'Mudanças não salvas',
  'builder.editor.clean': 'Tudo salvo',
  'builder.editor.previewToggle.show': 'Mostrar preview',
  'builder.editor.previewToggle.hide': 'Esconder preview',
  'builder.editor.save': 'Salvar',
  'builder.editor.saving': 'Salvando…',
  'builder.editor.saved': 'Salvo em scenarios/{folder}',
  'builder.editor.saveShortcut': 'Ctrl+S salva',
  'builder.editor.save.error.title': 'Não consegui salvar',
  'builder.editor.save.error.body': 'Parte dos arquivos pode ter sido escrita. Recarregue do disco antes de tentar de novo.',
  'builder.editor.save.error.disabled.title': 'Salvar está desligado',
  'builder.editor.save.error.disabled.body':
    'A flag builder está desligada em ~/.ooc-local/config.yaml. Ligue de novo para gravar no disco.',
  'builder.editor.save.error.validationOne': '1 campo precisa de conserto antes de salvar.',
  'builder.editor.save.error.validationOther': '{count} campos precisam de conserto antes de salvar.',
  'builder.editor.save.error.conflict.title': 'Os arquivos mudaram no disco',
  'builder.editor.save.error.conflict.body':
    "scenarios/{folder} foi editado fora do app depois que você abriu. Recarregue para ficar com a versão do disco, ou sobrescreva para manter o que está nesta tela.",
  'builder.editor.conflict.reload': 'Recarregar e perder minhas edições',
  'builder.editor.conflict.overwrite': 'Sobrescrever os arquivos',
  'builder.editor.reload': 'Recarregar do disco',
  'builder.editor.reload.confirmTitle': 'Descartar suas mudanças não salvas?',
  'builder.editor.reload.confirmBody': 'Recarregar lê os arquivos de novo e joga fora o que você editou aqui.',
  'builder.editor.reload.confirmSubmit': 'Recarregar e descartar',
  'builder.editor.reloaded': 'Recarregado do disco',
  'builder.editor.leave.title': 'Sair sem salvar?',
  'builder.editor.leave.body': '{scenario} tem mudanças não salvas. Elas só existem nesta aba.',
  'builder.editor.leave.stay': 'Continuar editando',
  'builder.editor.leave.saveAndLeave': 'Salvar e sair',
  'builder.editor.leave.discard': 'Sair e descartar',
  'builder.editor.validation.summaryTitle': 'Conserte isto antes de salvar',
  'builder.editor.validation.jump': 'Ir para {field}',

  // Builder field patterns (shared by identity, world, starts and characters tabs)
  'builder.field.required': 'Este campo é obrigatório.',
  'builder.field.tooLong': 'Longo demais — máximo de {max} caracteres.',
  'builder.field.counter': '{count}/{max}',
  'builder.field.slugInvalid': 'Use só letras minúsculas, números e hífens.',
  'builder.field.slugTaken': '{slug} já está em uso neste cenário.',
  'builder.detail.selected': 'Editando {name}',

  // Media errors (shared by identity, media/sprites and media/backgrounds tabs)
  'builder.media.error.type': 'Só imagens PNG, JPEG e WebP.',
  'builder.media.error.size': 'A imagem passa de {max} MB. Reduza e tente de novo.',
  'builder.media.error.write': 'O arquivo não foi escrito. Confira se a pasta media aceita escrita.',
  'builder.media.error.removeFailed': 'O arquivo não foi removido. Ele continua no disco.',
  'builder.media.error.disabled': 'A escrita está desligada: a flag builder está desligada em ~/.ooc-local/config.yaml.',

  // Builder editor identity tab
  'builder.identity.heading': 'Identidade',
  'builder.identity.name': 'Nome',
  'builder.identity.tagline': 'Tagline',
  'builder.identity.tagline.hint': 'Uma linha, mostrada ao lado do nome do cenário.',
  'builder.identity.description': 'Descrição',
  'builder.identity.description.hint': 'Markdown. Mostrada ao jogador antes de começar.',
  'builder.identity.tags': 'Tags',
  'builder.identity.tags.hint': 'Enter ou vírgula adiciona uma tag.',
  'builder.identity.tags.empty': 'Nenhuma tag ainda.',
  'builder.identity.tags.remove': 'Remover a tag {tag}',
  'builder.identity.tags.duplicate': '{tag} já está na lista.',
  'builder.identity.tags.max': 'Até 12 tags.',
  'builder.identity.locale': 'Idioma do cenário',
  'builder.identity.locale.hint': 'Define o idioma dos prompts de sistema, não o desta interface.',
  'builder.identity.cover.legend': 'Capa',
  'builder.identity.cover.hint': 'Salva em media/cover assim que você envia.',
  'builder.identity.cover.empty': 'Sem capa ainda',
  'builder.identity.cover.upload': 'Enviar uma capa',
  'builder.identity.cover.replace': 'Trocar a capa',
  'builder.identity.cover.remove': 'Remover a capa',
  'builder.identity.cover.uploading': 'Enviando a capa…',
  'builder.identity.cover.error': 'A capa não foi salva. Tente de novo.',
  'builder.identity.cover.alt': 'Capa de {scenario}',

  // Game screen
  'game.documentTitle': '{scenario} — ooc-local',
  'game.loading': 'Carregando sessão…',
  'game.back': 'Voltar para as sessões',
  'game.prologue.label': 'Prólogo',
  'game.empty.hint': 'Sua vez. Escreva o que você faz ou fala.',
  'game.input.label': 'Sua ação',
  'game.input.placeholder': 'O que você faz?',
  'game.input.send': 'Enviar',
  'game.input.sending': 'Narrando…',
  'game.input.hint': 'Enter envia · Shift+Enter quebra linha',
  'game.turn.playerLabel': 'Você',
  'game.turn.narratorLabel': 'Narrador',
  'game.turn.thinking': 'O narrador está escrevendo…',
  'game.turn.done': 'Turno {index} pronto',
  'game.turn.partial': 'Turno incompleto',
  'game.turn.error': 'O turno parou no meio',
  'game.turn.errorBody': 'O narrador não terminou. Sua mensagem foi guardada — mande de novo.',
  'game.scrollToLatest': 'Ir para o mais recente',
  'game.notFound.title': 'Sessão não encontrada',
  'game.notFound.body': 'Essa sessão não existe mais. Volte e escolha outra.',

  // HUD
  'hud.turn': 'Turno',
  'hud.location': 'Local',
  'hud.time': 'Hora',
  'hud.weather': 'Clima',
  'hud.placeholder': '—',
  'hud.unavailable': 'Ainda não rastreado',
  'hud.stale': 'Mostrando o último estado conhecido',
  'hud.announce': 'Turno {turn}, {location}, {time}, {weather}',
  'hud.weather.clear': 'Limpo',
  'hud.weather.cloudy': 'Nublado',
  'hud.weather.rain': 'Chuva',
  'hud.weather.storm': 'Tempestade',
  'hud.weather.snow': 'Neve',
  'hud.weather.fog': 'Neblina',
  'hud.weather.night': 'Noite',
  'hud.weather.unknown': 'Desconhecido',

  // Turn text
  'turnText.speakerLabel': '{name} diz',
  'turnText.narrationLabel': 'Narração',
  'turnText.rawFallback': 'Mostrado como o narrador escreveu',
}

export const strings = { en, 'pt-br': ptBr }
